//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SanctionLists.Parsers.EuParser.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SanctionLists.Parsers.EuParser.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!-- GENERATED BY FSD --&gt;
        ///&lt;WHOLE Date=&quot;14/08/2015&quot;&gt;
        ///&lt;ENTITY Id=&quot;1&quot; Type=&quot;P&quot; legal_basis=&quot;151/2012 (OJ L49)&quot; reg_date=&quot;2012-02-21&quot; pdf_link=&quot;http://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=OJ:L:2012:049:0002:0016:EN:PDF&quot; programme=&quot;ZWE&quot; remark=&quot;(Entity is sanctioned in regime 310/2002 (OJ L50) of programme ZWE, in regime 314/2004 (OJ L55) of programme ZWE)&quot;&gt;
        ///&lt;NAME Id=&quot;1&quot; Entity_id=&quot;1&quot; legal_basis=&quot;898/2005 (OJ L153)&quot; reg_date=&quot;2005-06-16&quot; pdf_link=&quot;http://eur-lex. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string global {
            get {
                return ResourceManager.GetString("global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;export xmlns=&quot;http://eu.europa.ec/fpi/fsd/export&quot; generationDate=&quot;2015-08-14T12:22:32.276+02:00&quot; globalFileId=&quot;105988&quot;&gt;
        ///   &lt;sanctionEntity logicalId=&quot;1&quot; designationDetails=&quot;&quot; unitedNationId=&quot;&quot;&gt;
        ///      &lt;regulation logicalId=&quot;1328&quot; regulationType=&quot;amendment&quot; organisationType=&quot;commission&quot; publicationDate=&quot;2012-02-22&quot; entryIntoForceDate=&quot;2012-02-21&quot; numberTitle=&quot;151/2012 (OJ L49)&quot; programme=&quot;ZWE&quot;&gt;
        ///         &lt;publicationUrl&gt;http://eur-lex.europa.eu/LexUriServ/LexUriServ.do?u [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string global_fsd {
            get {
                return ResourceManager.GetString("global_fsd", resourceCulture);
            }
        }
    }
}
