//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BND.Services.Security.OTP.Plugins.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BND.Services.Security.OTP.Plugins.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to key.
        /// </summary>
        internal static string AttrKey {
            get {
                return ResourceManager.GetString("AttrKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        internal static string AttrName {
            get {
                return ResourceManager.GetString("AttrName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value.
        /// </summary>
        internal static string AttrValue {
            get {
                return ResourceManager.GetString("AttrValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version.
        /// </summary>
        internal static string AttrVersion {
            get {
                return ResourceManager.GetString("AttrVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin must has Attribute ReaderExportAttribute on class..
        /// </summary>
        internal static string Class_No_Attribute {
            get {
                return ResourceManager.GetString("Class_No_Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; key attribute of &apos;parameter&apos; tag is duplicate underneath &apos;parameters&apos; tag..
        /// </summary>
        internal static string ErrorAttrKeyDuplicate {
            get {
                return ResourceManager.GetString("ErrorAttrKeyDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;key&apos; and &apos;value&apos; attributes are required underneath &apos;parameter&apos; tag..
        /// </summary>
        internal static string ErrorAttrKeyValueNotFound {
            get {
                return ResourceManager.GetString("ErrorAttrKeyValueNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel &apos;{0}&apos; could not be found in plugin setting file..
        /// </summary>
        internal static string ErrorSettingChannelNotFound {
            get {
                return ResourceManager.GetString("ErrorSettingChannelNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin setting file could not be found..
        /// </summary>
        internal static string ErrorSettingNotFound {
            get {
                return ResourceManager.GetString("ErrorSettingNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin setting file has to be xml format..
        /// </summary>
        internal static string ErrorSettingNotXml {
            get {
                return ResourceManager.GetString("ErrorSettingNotXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;parameters&apos; tag is required underneath &apos;plugin-setting&apos; tag..
        /// </summary>
        internal static string ErrorTagParametersNotFound {
            get {
                return ResourceManager.GetString("ErrorTagParametersNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parameter.
        /// </summary>
        internal static string TagParameter {
            get {
                return ResourceManager.GetString("TagParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parameters.
        /// </summary>
        internal static string TagParameters {
            get {
                return ResourceManager.GetString("TagParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plugin-settings/plugin-setting[@name=&apos;{0}&apos;].
        /// </summary>
        internal static string XpathRoot {
            get {
                return ResourceManager.GetString("XpathRoot", resourceCulture);
            }
        }
    }
}
