CREATE TABLE [ideal].[Transaction]
(
    [TransactionID] VARCHAR(16) NOT NULL PRIMARY KEY, 
    [AcquirerID] VARCHAR(4) NOT NULL, 
    [MerchantID] VARCHAR(9) NOT NULL, 
    [SubID] INT NULL, 
    [IssuerID] VARCHAR(11) NOT NULL, 
    [IssuerAuthenticationURL] VARCHAR(512) NULL, 
    [MerchantReturnURL] VARCHAR(512) NOT NULL, 
    [EntranceCode] VARCHAR(40) NOT NULL, 
    [PurchaseID] VARCHAR(35) NOT NULL, 
    [Amount] DECIMAL(12, 2) NOT NULL, 
    [Currency] VARCHAR(3) NOT NULL, 
    [Language] VARCHAR(2) NOT NULL, 
    [Description] NVARCHAR(35) NULL, 
    [ConsumerName] NVARCHAR(70) NULL, 
    [ConsumerIBAN] VARCHAR(34) NULL, 
    [ConsumerBIC] VARCHAR(11) NULL, 
    [TransactionRequestDateTimestamp] DATETIME NOT NULL, 
    [TransactionResponseDateTimestamp] DATETIME NOT NULL, 
    [TransactionCreateDateTimestamp] DATETIME NOT NULL, 
    [BNDIBAN] NVARCHAR(34) NOT NULL, 
    [PaymentType] VARCHAR(64) NOT NULL, 
    [ExpirationSecondPeriod] INT NOT NULL, 
    [ExpectedCustomerIBAN] VARCHAR(34) NOT NULL, 
    [IsSystemFail] BIT NOT NULL, 
    [TodayAttempts] INT NOT NULL, 
    [LatestAttemptsDateTimestamp] DATETIME NULL
)
