//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BND.Services.Matrix.Resources.Business {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MatrixManager {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MatrixManager() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BND.Services.Matrix.Resources.Business.MatrixManager", typeof(MatrixManager).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source and destination accounts are the same!.
        /// </summary>
        public static string AccountsAreSame {
            get {
                return ResourceManager.GetString("AccountsAreSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount should Not Be Zero!.
        /// </summary>
        public static string AmountShouldNotBeZero {
            get {
                return ResourceManager.GetString("AmountShouldNotBeZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CenterName was not found!.
        /// </summary>
        public static string CenterNameWasNotFound {
            get {
                return ResourceManager.GetString("CenterNameWasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a valid closing payment item!.
        /// </summary>
        public static string ClosingPaymentItemIsNull {
            get {
                return ResourceManager.GetString("ClosingPaymentItemIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem getting the account from account type!.
        /// </summary>
        public static string CouldNotResolveAccountFromAccountType {
            get {
                return ResourceManager.GetString("CouldNotResolveAccountFromAccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CounterpartyBIC should not be null!.
        /// </summary>
        public static string CounterpartyBicShouldNotBeNull {
            get {
                return ResourceManager.GetString("CounterpartyBicShouldNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CounterpartyIBAN should not be null!.
        /// </summary>
        public static string CounterpartyIBANShouldNotBeNull {
            get {
                return ResourceManager.GetString("CounterpartyIBANShouldNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creditor&apos;s city should not be null!.
        /// </summary>
        public static string CreditorsCityShouldNotBeNull {
            get {
                return ResourceManager.GetString("CreditorsCityShouldNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creditor&apos;s country code should not be null!.
        /// </summary>
        public static string CreditorsCountryCodeShouldNotBeNull {
            get {
                return ResourceManager.GetString("CreditorsCountryCodeShouldNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creditor should not be null!.
        /// </summary>
        public static string CreditorShouldNotBeNull {
            get {
                return ResourceManager.GetString("CreditorShouldNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creditor&apos;s name should not be null!.
        /// </summary>
        public static string CreditorsNameShouldNotBeNull {
            get {
                return ResourceManager.GetString("CreditorsNameShouldNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creditor&apos;s postcode should not be null!.
        /// </summary>
        public static string CreditorsPostcodeShouldNotBeNull {
            get {
                return ResourceManager.GetString("CreditorsPostcodeShouldNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creditor&apos;s street should not be null!.
        /// </summary>
        public static string CreditorsStreetShouldNotBeNull {
            get {
                return ResourceManager.GetString("CreditorsStreetShouldNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a start date or an end date!.
        /// </summary>
        public static string DateNotEntered {
            get {
                return ResourceManager.GetString("DateNotEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debtor&apos;s city should not be null!.
        /// </summary>
        public static string DebtorsCityShouldNotBeNull {
            get {
                return ResourceManager.GetString("DebtorsCityShouldNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debtor&apos;s country code should not be null!.
        /// </summary>
        public static string DebtorsCountryCodeShouldNotBeNull {
            get {
                return ResourceManager.GetString("DebtorsCountryCodeShouldNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debtor should not be null!.
        /// </summary>
        public static string DebtorShouldNotBeNull {
            get {
                return ResourceManager.GetString("DebtorShouldNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debtor&apos;s name should not be null!.
        /// </summary>
        public static string DebtorsNameShouldNotBeNull {
            get {
                return ResourceManager.GetString("DebtorsNameShouldNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debtor&apos;s postcode should not be null!.
        /// </summary>
        public static string DebtorsPostcodeShouldNotBeNull {
            get {
                return ResourceManager.GetString("DebtorsPostcodeShouldNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debtor&apos;s street should not be null!.
        /// </summary>
        public static string DebtorsStreetShouldNotBeNull {
            get {
                return ResourceManager.GetString("DebtorsStreetShouldNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The department was not found!.
        /// </summary>
        public static string DepartmentWasNotFound {
            get {
                return ResourceManager.GetString("DepartmentWasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sweep entity cannot be null!.
        /// </summary>
        public static string EmptySweepEntity {
            get {
                return ResourceManager.GetString("EmptySweepEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end date must be bigger than the start date!.
        /// </summary>
        public static string EndDateMustBeBigger {
            get {
                return ResourceManager.GetString("EndDateMustBeBigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iban Not Consistent With Source Iban!.
        /// </summary>
        public static string IbanNotConsistentWithSourceIban {
            get {
                return ResourceManager.GetString("IbanNotConsistentWithSourceIban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify an IBAN!.
        /// </summary>
        public static string IBANNotGiven {
            get {
                return ResourceManager.GetString("IBANNotGiven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id not given!.
        /// </summary>
        public static string IdNotGiven {
            get {
                return ResourceManager.GetString("IdNotGiven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified message type is invalid!.
        /// </summary>
        public static string InvalidMessageType {
            get {
                return ResourceManager.GetString("InvalidMessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Date was provided!.
        /// </summary>
        public static string NoDateProvided {
            get {
                return ResourceManager.GetString("NoDateProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one type of Account has to be provided!.
        /// </summary>
        public static string NoSystemAccountProvided {
            get {
                return ResourceManager.GetString("NoSystemAccountProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An account type has to be specified!.
        /// </summary>
        public static string NotSetAccount {
            get {
                return ResourceManager.GetString("NotSetAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a valid start date!.
        /// </summary>
        public static string NotValidStartDate {
            get {
                return ResourceManager.GetString("NotValidStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a valid value date!.
        /// </summary>
        public static string NotValidValueDate {
            get {
                return ResourceManager.GetString("NotValidValueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid return bucket!.
        /// </summary>
        public static string NullReturnBucket {
            get {
                return ResourceManager.GetString("NullReturnBucket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment not given!.
        /// </summary>
        public static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment was not given!.
        /// </summary>
        public static string PaymentNotGiven {
            get {
                return ResourceManager.GetString("PaymentNotGiven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Savings Account given should not be null!.
        /// </summary>
        public static string SavingsNull {
            get {
                return ResourceManager.GetString("SavingsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Savings Product was not found!.
        /// </summary>
        public static string SavingsProductNotFound {
            get {
                return ResourceManager.GetString("SavingsProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit was not found!.
        /// </summary>
        public static string UnitWasNotFound {
            get {
                return ResourceManager.GetString("UnitWasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both accounts have to be specified!.
        /// </summary>
        public static string UnspecifiedAccount {
            get {
                return ResourceManager.GetString("UnspecifiedAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount should be greater than zero!.
        /// </summary>
        public static string ZeroAmount {
            get {
                return ResourceManager.GetString("ZeroAmount", resourceCulture);
            }
        }
    }
}
