namespace BND.Services.Payments.PaymentIdInfo.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    /// <summary>
    /// Class p_TransactionStatusHistory.
    /// </summary>
    [Table("ideal.TransactionStatusHistory")]
    public partial class p_iDealTransactionStatusHistory
    {
        /// <summary>
        /// Gets or sets the transaction status history identifier.
        /// </summary>
        [Key]
        public int TransactionStatusHistoryID { get; set; }
        /// <summary>
        /// Unique 16-digit number within iDEAL. The number consists of the acquirerID (first four positions) and a unique number generated by the 
        /// Acquirer(12 positions). Ultimately appears on payment confirmation (bank statement or account overview of the Consumer and Merchant).
        /// </summary>
        [Required]
        [StringLength(16)]
        public string TransactionID { get; set; }
        /// <summary>
        /// Gets or sets the transaction status.
        /// </summary>
        [Required]
        [StringLength(32)]
        public string Status { get; set; }
        /// <summary>
        /// Gets or sets the status request date time stamp.
        /// </summary>
        public DateTime StatusRequestDateTimeStamp { get; set; }
        /// <summary>
        /// Gets or sets the status response date time stamp.
        /// </summary>
        public DateTime StatusResponseDateTimeStamp { get; set; }
        /// <summary>
        /// Gets or sets the status date time stamp.
        /// </summary>
        public DateTime? StatusDateTimeStamp { get; set; }
        /// <summary>
        /// Gets or sets the transaction.
        /// </summary>
        public virtual p_iDealTransaction Transaction { get; set; }
    }
}
