//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BND.Services.Payments.PaymentIdInfo.Proxy.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BND.Services.Payments.PaymentIdInfo.Proxy.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?filtertype={0}.
        /// </summary>
        internal static string FILTER_TYPE {
            get {
                return ResourceManager.GetString("FILTER_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        internal static string KEY {
            get {
                return ResourceManager.GetString("KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        internal static string SEPARATOR {
            get {
                return ResourceManager.GetString("SEPARATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/.
        /// </summary>
        internal static string URL_RES_BASE {
            get {
                return ResourceManager.GetString("URL_RES_BASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaymentIdInfos/GetFilterTypes.
        /// </summary>
        internal static string URL_RES_GET_FILTERTYPE {
            get {
                return ResourceManager.GetString("URL_RES_GET_FILTERTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaymentIdInfos/BndIban/{0}.
        /// </summary>
        internal static string URL_RES_PAYMENTIDINFO_BY_BNDIBAN {
            get {
                return ResourceManager.GetString("URL_RES_PAYMENTIDINFO_BY_BNDIBAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaymentIdInfos/SourceIban/{0}.
        /// </summary>
        internal static string URL_RES_PAYMENTIDINFO_BY_SOURCEIBAN {
            get {
                return ResourceManager.GetString("URL_RES_PAYMENTIDINFO_BY_SOURCEIBAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaymentIdInfos/Transaction/{0}.
        /// </summary>
        internal static string URL_RES_PAYMENTIDINFO_BY_TRANSACTION {
            get {
                return ResourceManager.GetString("URL_RES_PAYMENTIDINFO_BY_TRANSACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string VALUE {
            get {
                return ResourceManager.GetString("VALUE", resourceCulture);
            }
        }
    }
}
