//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BND.Services.Security.OTP.Api.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BND.Services.Security.OTP.Api.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OtpDb.
        /// </summary>
        internal static string DB_CONN_KEY {
            get {
                return ResourceManager.GetString("DB_CONN_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account has been locked, please contact administrator..
        /// </summary>
        internal static string ErrorAccountIsLocked {
            get {
                return ResourceManager.GetString("ErrorAccountIsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; cannot be null..
        /// </summary>
        internal static string ErrorArgNull {
            get {
                return ResourceManager.GetString("ErrorArgNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; channel type could not be found..
        /// </summary>
        internal static string ErrorChannelNotFound {
            get {
                return ResourceManager.GetString("ErrorChannelNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suid cannot duplicate. please change suid then re-send again..
        /// </summary>
        internal static string ErrorDuplicateSuid {
            get {
                return ResourceManager.GetString("ErrorDuplicateSuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; header is required..
        /// </summary>
        internal static string ErrorHeaderRequired {
            get {
                return ResourceManager.GetString("ErrorHeaderRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; could not be found..
        /// </summary>
        internal static string ErrorNotFound {
            get {
                return ResourceManager.GetString("ErrorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This otp code is invalid..
        /// </summary>
        internal static string ErrorOtpInvalid {
            get {
                return ResourceManager.GetString("ErrorOtpInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This otp code has {0}..
        /// </summary>
        internal static string ErrorOtpInvalidStatusActive {
            get {
                return ResourceManager.GetString("ErrorOtpInvalidStatusActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have to add new error message for status &apos;{0}&apos;..
        /// </summary>
        internal static string ErrorOtpInvalidStatusNotImplement {
            get {
                return ResourceManager.GetString("ErrorOtpInvalidStatusNotImplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have to add new  status &apos;{0}&apos; to &apos;OtpStatus&apos; enum..
        /// </summary>
        internal static string ErrorOtpInvalidStatusNotSupport {
            get {
                return ResourceManager.GetString("ErrorOtpInvalidStatusNotSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This otp code has been {0}..
        /// </summary>
        internal static string ErrorOtpInvalidStatusPassive {
            get {
                return ResourceManager.GetString("ErrorOtpInvalidStatusPassive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error result could not be &apos;{0}&apos; status code..
        /// </summary>
        internal static string ErrorWrongHttpStatus {
            get {
                return ResourceManager.GetString("ErrorWrongHttpStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account-Id and/or Api-key are wrong..
        /// </summary>
        internal static string ErrrorUnauthorized {
            get {
                return ResourceManager.GetString("ErrrorUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account-Id.
        /// </summary>
        internal static string HEADER_ACC_ID {
            get {
                return ResourceManager.GetString("HEADER_ACC_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization.
        /// </summary>
        internal static string HEADER_AUTH {
            get {
                return ResourceManager.GetString("HEADER_AUTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChannelPlugins.
        /// </summary>
        internal static string PLUGIN_FOLDER {
            get {
                return ResourceManager.GetString("PLUGIN_FOLDER", resourceCulture);
            }
        }
    }
}
