//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.33440.
// 


/// <remarks/>
// CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="IApprovalService_Endpoint", Namespace="http://service.matrix.financials.fivedegrees.nl/1.0")]
public partial class ApprovalServiceBSL : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback GetApprovalTypesOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetApprovalRequestsOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetApprovalOperationCompleted;
    
    private System.Threading.SendOrPostCallback CreateApprovalTypeOperationCompleted;
    
    private System.Threading.SendOrPostCallback DeleteApprovalTypeOperationCompleted;
    
    private System.Threading.SendOrPostCallback UpdateApprovalTypeOperationCompleted;
    
    private System.Threading.SendOrPostCallback ApproveOperationCompleted;
    
    private System.Threading.SendOrPostCallback RejectOperationCompleted;
    
    /// <remarks/>
    public ApprovalServiceBSL() {
        this.Url = "https://localhost:44302/Service.svc";
    }
    
    /// <remarks/>
    public event GetApprovalTypesCompletedEventHandler GetApprovalTypesCompleted;
    
    /// <remarks/>
    public event GetApprovalRequestsCompletedEventHandler GetApprovalRequestsCompleted;
    
    /// <remarks/>
    public event GetApprovalCompletedEventHandler GetApprovalCompleted;
    
    /// <remarks/>
    public event CreateApprovalTypeCompletedEventHandler CreateApprovalTypeCompleted;
    
    /// <remarks/>
    public event DeleteApprovalTypeCompletedEventHandler DeleteApprovalTypeCompleted;
    
    /// <remarks/>
    public event UpdateApprovalTypeCompletedEventHandler UpdateApprovalTypeCompleted;
    
    /// <remarks/>
    public event ApproveCompletedEventHandler ApproveCompleted;
    
    /// <remarks/>
    public event RejectCompletedEventHandler RejectCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.matrix.financials.fivedegrees.nl/1.0/IApprovalService/GetApprovalT" +
        "ypes", RequestNamespace="http://service.matrix.financials.fivedegrees.nl/1.0", ResponseNamespace="http://service.matrix.financials.fivedegrees.nl/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public OperationResult_ArrayOfApprovalTypeItem GetApprovalTypes(string correlationId, int centerId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool centerIdSpecified) {
        object[] results = this.Invoke("GetApprovalTypes", new object[] {
                    correlationId,
                    centerId,
                    centerIdSpecified});
        return ((OperationResult_ArrayOfApprovalTypeItem)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetApprovalTypes(string correlationId, int centerId, bool centerIdSpecified, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetApprovalTypes", new object[] {
                    correlationId,
                    centerId,
                    centerIdSpecified}, callback, asyncState);
    }
    
    /// <remarks/>
    public OperationResult_ArrayOfApprovalTypeItem EndGetApprovalTypes(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((OperationResult_ArrayOfApprovalTypeItem)(results[0]));
    }
    
    /// <remarks/>
    public void GetApprovalTypesAsync(string correlationId, int centerId, bool centerIdSpecified) {
        this.GetApprovalTypesAsync(correlationId, centerId, centerIdSpecified, null);
    }
    
    /// <remarks/>
    public void GetApprovalTypesAsync(string correlationId, int centerId, bool centerIdSpecified, object userState) {
        if ((this.GetApprovalTypesOperationCompleted == null)) {
            this.GetApprovalTypesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetApprovalTypesOperationCompleted);
        }
        this.InvokeAsync("GetApprovalTypes", new object[] {
                    correlationId,
                    centerId,
                    centerIdSpecified}, this.GetApprovalTypesOperationCompleted, userState);
    }
    
    private void OnGetApprovalTypesOperationCompleted(object arg) {
        if ((this.GetApprovalTypesCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetApprovalTypesCompleted(this, new GetApprovalTypesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.matrix.financials.fivedegrees.nl/1.0/IApprovalService/GetApprovalR" +
        "equests", RequestNamespace="http://service.matrix.financials.fivedegrees.nl/1.0", ResponseNamespace="http://service.matrix.financials.fivedegrees.nl/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public OperationResult_ArrayOfApprovalRequestItem GetApprovalRequests(string correlationId, int centerId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool centerIdSpecified) {
        object[] results = this.Invoke("GetApprovalRequests", new object[] {
                    correlationId,
                    centerId,
                    centerIdSpecified});
        return ((OperationResult_ArrayOfApprovalRequestItem)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetApprovalRequests(string correlationId, int centerId, bool centerIdSpecified, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetApprovalRequests", new object[] {
                    correlationId,
                    centerId,
                    centerIdSpecified}, callback, asyncState);
    }
    
    /// <remarks/>
    public OperationResult_ArrayOfApprovalRequestItem EndGetApprovalRequests(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((OperationResult_ArrayOfApprovalRequestItem)(results[0]));
    }
    
    /// <remarks/>
    public void GetApprovalRequestsAsync(string correlationId, int centerId, bool centerIdSpecified) {
        this.GetApprovalRequestsAsync(correlationId, centerId, centerIdSpecified, null);
    }
    
    /// <remarks/>
    public void GetApprovalRequestsAsync(string correlationId, int centerId, bool centerIdSpecified, object userState) {
        if ((this.GetApprovalRequestsOperationCompleted == null)) {
            this.GetApprovalRequestsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetApprovalRequestsOperationCompleted);
        }
        this.InvokeAsync("GetApprovalRequests", new object[] {
                    correlationId,
                    centerId,
                    centerIdSpecified}, this.GetApprovalRequestsOperationCompleted, userState);
    }
    
    private void OnGetApprovalRequestsOperationCompleted(object arg) {
        if ((this.GetApprovalRequestsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetApprovalRequestsCompleted(this, new GetApprovalRequestsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.matrix.financials.fivedegrees.nl/1.0/IApprovalService/GetApproval", RequestNamespace="http://service.matrix.financials.fivedegrees.nl/1.0", ResponseNamespace="http://service.matrix.financials.fivedegrees.nl/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public OperationResult_ApprovalRequestItem GetApproval(string correlationId, int centerId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool centerIdSpecified, string instanceId) {
        object[] results = this.Invoke("GetApproval", new object[] {
                    correlationId,
                    centerId,
                    centerIdSpecified,
                    instanceId});
        return ((OperationResult_ApprovalRequestItem)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetApproval(string correlationId, int centerId, bool centerIdSpecified, string instanceId, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetApproval", new object[] {
                    correlationId,
                    centerId,
                    centerIdSpecified,
                    instanceId}, callback, asyncState);
    }
    
    /// <remarks/>
    public OperationResult_ApprovalRequestItem EndGetApproval(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((OperationResult_ApprovalRequestItem)(results[0]));
    }
    
    /// <remarks/>
    public void GetApprovalAsync(string correlationId, int centerId, bool centerIdSpecified, string instanceId) {
        this.GetApprovalAsync(correlationId, centerId, centerIdSpecified, instanceId, null);
    }
    
    /// <remarks/>
    public void GetApprovalAsync(string correlationId, int centerId, bool centerIdSpecified, string instanceId, object userState) {
        if ((this.GetApprovalOperationCompleted == null)) {
            this.GetApprovalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetApprovalOperationCompleted);
        }
        this.InvokeAsync("GetApproval", new object[] {
                    correlationId,
                    centerId,
                    centerIdSpecified,
                    instanceId}, this.GetApprovalOperationCompleted, userState);
    }
    
    private void OnGetApprovalOperationCompleted(object arg) {
        if ((this.GetApprovalCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetApprovalCompleted(this, new GetApprovalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.matrix.financials.fivedegrees.nl/1.0/IApprovalService/CreateApprov" +
        "alType", RequestNamespace="http://service.matrix.financials.fivedegrees.nl/1.0", ResponseNamespace="http://service.matrix.financials.fivedegrees.nl/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public OperationResult_int CreateApprovalType(string correlationId, int centerId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool centerIdSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] CreateApprovalTypeItem createApprovalTypeItem) {
        object[] results = this.Invoke("CreateApprovalType", new object[] {
                    correlationId,
                    centerId,
                    centerIdSpecified,
                    createApprovalTypeItem});
        return ((OperationResult_int)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginCreateApprovalType(string correlationId, int centerId, bool centerIdSpecified, CreateApprovalTypeItem createApprovalTypeItem, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("CreateApprovalType", new object[] {
                    correlationId,
                    centerId,
                    centerIdSpecified,
                    createApprovalTypeItem}, callback, asyncState);
    }
    
    /// <remarks/>
    public OperationResult_int EndCreateApprovalType(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((OperationResult_int)(results[0]));
    }
    
    /// <remarks/>
    public void CreateApprovalTypeAsync(string correlationId, int centerId, bool centerIdSpecified, CreateApprovalTypeItem createApprovalTypeItem) {
        this.CreateApprovalTypeAsync(correlationId, centerId, centerIdSpecified, createApprovalTypeItem, null);
    }
    
    /// <remarks/>
    public void CreateApprovalTypeAsync(string correlationId, int centerId, bool centerIdSpecified, CreateApprovalTypeItem createApprovalTypeItem, object userState) {
        if ((this.CreateApprovalTypeOperationCompleted == null)) {
            this.CreateApprovalTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateApprovalTypeOperationCompleted);
        }
        this.InvokeAsync("CreateApprovalType", new object[] {
                    correlationId,
                    centerId,
                    centerIdSpecified,
                    createApprovalTypeItem}, this.CreateApprovalTypeOperationCompleted, userState);
    }
    
    private void OnCreateApprovalTypeOperationCompleted(object arg) {
        if ((this.CreateApprovalTypeCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.CreateApprovalTypeCompleted(this, new CreateApprovalTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.matrix.financials.fivedegrees.nl/1.0/IApprovalService/DeleteApprov" +
        "alType", RequestNamespace="http://service.matrix.financials.fivedegrees.nl/1.0", ResponseNamespace="http://service.matrix.financials.fivedegrees.nl/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public OperationResult_boolean DeleteApprovalType(string correlationId, int centerId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool centerIdSpecified, int approvalId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool approvalIdSpecified) {
        object[] results = this.Invoke("DeleteApprovalType", new object[] {
                    correlationId,
                    centerId,
                    centerIdSpecified,
                    approvalId,
                    approvalIdSpecified});
        return ((OperationResult_boolean)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginDeleteApprovalType(string correlationId, int centerId, bool centerIdSpecified, int approvalId, bool approvalIdSpecified, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("DeleteApprovalType", new object[] {
                    correlationId,
                    centerId,
                    centerIdSpecified,
                    approvalId,
                    approvalIdSpecified}, callback, asyncState);
    }
    
    /// <remarks/>
    public OperationResult_boolean EndDeleteApprovalType(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((OperationResult_boolean)(results[0]));
    }
    
    /// <remarks/>
    public void DeleteApprovalTypeAsync(string correlationId, int centerId, bool centerIdSpecified, int approvalId, bool approvalIdSpecified) {
        this.DeleteApprovalTypeAsync(correlationId, centerId, centerIdSpecified, approvalId, approvalIdSpecified, null);
    }
    
    /// <remarks/>
    public void DeleteApprovalTypeAsync(string correlationId, int centerId, bool centerIdSpecified, int approvalId, bool approvalIdSpecified, object userState) {
        if ((this.DeleteApprovalTypeOperationCompleted == null)) {
            this.DeleteApprovalTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteApprovalTypeOperationCompleted);
        }
        this.InvokeAsync("DeleteApprovalType", new object[] {
                    correlationId,
                    centerId,
                    centerIdSpecified,
                    approvalId,
                    approvalIdSpecified}, this.DeleteApprovalTypeOperationCompleted, userState);
    }
    
    private void OnDeleteApprovalTypeOperationCompleted(object arg) {
        if ((this.DeleteApprovalTypeCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.DeleteApprovalTypeCompleted(this, new DeleteApprovalTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.matrix.financials.fivedegrees.nl/1.0/IApprovalService/UpdateApprov" +
        "alType", RequestNamespace="http://service.matrix.financials.fivedegrees.nl/1.0", ResponseNamespace="http://service.matrix.financials.fivedegrees.nl/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public OperationResult_boolean UpdateApprovalType(string correlationId, int centerId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool centerIdSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] UpdateApprovalTypeItem updateApprovalTypeItem) {
        object[] results = this.Invoke("UpdateApprovalType", new object[] {
                    correlationId,
                    centerId,
                    centerIdSpecified,
                    updateApprovalTypeItem});
        return ((OperationResult_boolean)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginUpdateApprovalType(string correlationId, int centerId, bool centerIdSpecified, UpdateApprovalTypeItem updateApprovalTypeItem, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("UpdateApprovalType", new object[] {
                    correlationId,
                    centerId,
                    centerIdSpecified,
                    updateApprovalTypeItem}, callback, asyncState);
    }
    
    /// <remarks/>
    public OperationResult_boolean EndUpdateApprovalType(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((OperationResult_boolean)(results[0]));
    }
    
    /// <remarks/>
    public void UpdateApprovalTypeAsync(string correlationId, int centerId, bool centerIdSpecified, UpdateApprovalTypeItem updateApprovalTypeItem) {
        this.UpdateApprovalTypeAsync(correlationId, centerId, centerIdSpecified, updateApprovalTypeItem, null);
    }
    
    /// <remarks/>
    public void UpdateApprovalTypeAsync(string correlationId, int centerId, bool centerIdSpecified, UpdateApprovalTypeItem updateApprovalTypeItem, object userState) {
        if ((this.UpdateApprovalTypeOperationCompleted == null)) {
            this.UpdateApprovalTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateApprovalTypeOperationCompleted);
        }
        this.InvokeAsync("UpdateApprovalType", new object[] {
                    correlationId,
                    centerId,
                    centerIdSpecified,
                    updateApprovalTypeItem}, this.UpdateApprovalTypeOperationCompleted, userState);
    }
    
    private void OnUpdateApprovalTypeOperationCompleted(object arg) {
        if ((this.UpdateApprovalTypeCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.UpdateApprovalTypeCompleted(this, new UpdateApprovalTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.matrix.financials.fivedegrees.nl/1.0/IApprovalService/Approve", RequestNamespace="http://service.matrix.financials.fivedegrees.nl/1.0", ResponseNamespace="http://service.matrix.financials.fivedegrees.nl/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public OperationResult_ApprovalStatusItem Approve(string correlationId, int centerId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool centerIdSpecified, string instanceId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string reason) {
        object[] results = this.Invoke("Approve", new object[] {
                    correlationId,
                    centerId,
                    centerIdSpecified,
                    instanceId,
                    reason});
        return ((OperationResult_ApprovalStatusItem)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginApprove(string correlationId, int centerId, bool centerIdSpecified, string instanceId, string reason, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Approve", new object[] {
                    correlationId,
                    centerId,
                    centerIdSpecified,
                    instanceId,
                    reason}, callback, asyncState);
    }
    
    /// <remarks/>
    public OperationResult_ApprovalStatusItem EndApprove(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((OperationResult_ApprovalStatusItem)(results[0]));
    }
    
    /// <remarks/>
    public void ApproveAsync(string correlationId, int centerId, bool centerIdSpecified, string instanceId, string reason) {
        this.ApproveAsync(correlationId, centerId, centerIdSpecified, instanceId, reason, null);
    }
    
    /// <remarks/>
    public void ApproveAsync(string correlationId, int centerId, bool centerIdSpecified, string instanceId, string reason, object userState) {
        if ((this.ApproveOperationCompleted == null)) {
            this.ApproveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnApproveOperationCompleted);
        }
        this.InvokeAsync("Approve", new object[] {
                    correlationId,
                    centerId,
                    centerIdSpecified,
                    instanceId,
                    reason}, this.ApproveOperationCompleted, userState);
    }
    
    private void OnApproveOperationCompleted(object arg) {
        if ((this.ApproveCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.ApproveCompleted(this, new ApproveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.matrix.financials.fivedegrees.nl/1.0/IApprovalService/Reject", RequestNamespace="http://service.matrix.financials.fivedegrees.nl/1.0", ResponseNamespace="http://service.matrix.financials.fivedegrees.nl/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public OperationResult_ApprovalStatusItem Reject(string correlationId, int centerId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool centerIdSpecified, string instanceId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string reason) {
        object[] results = this.Invoke("Reject", new object[] {
                    correlationId,
                    centerId,
                    centerIdSpecified,
                    instanceId,
                    reason});
        return ((OperationResult_ApprovalStatusItem)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginReject(string correlationId, int centerId, bool centerIdSpecified, string instanceId, string reason, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Reject", new object[] {
                    correlationId,
                    centerId,
                    centerIdSpecified,
                    instanceId,
                    reason}, callback, asyncState);
    }
    
    /// <remarks/>
    public OperationResult_ApprovalStatusItem EndReject(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((OperationResult_ApprovalStatusItem)(results[0]));
    }
    
    /// <remarks/>
    public void RejectAsync(string correlationId, int centerId, bool centerIdSpecified, string instanceId, string reason) {
        this.RejectAsync(correlationId, centerId, centerIdSpecified, instanceId, reason, null);
    }
    
    /// <remarks/>
    public void RejectAsync(string correlationId, int centerId, bool centerIdSpecified, string instanceId, string reason, object userState) {
        if ((this.RejectOperationCompleted == null)) {
            this.RejectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRejectOperationCompleted);
        }
        this.InvokeAsync("Reject", new object[] {
                    correlationId,
                    centerId,
                    centerIdSpecified,
                    instanceId,
                    reason}, this.RejectOperationCompleted, userState);
    }
    
    private void OnRejectOperationCompleted(object arg) {
        if ((this.RejectCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.RejectCompleted(this, new RejectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:OperationResult")]
public partial class OperationResult_ArrayOfApprovalTypeItem {
    
    private int resultCodeField;
    
    private long operationIdField;
    
    private string errorMessageField;
    
    private ApprovalTypeItem[] dataField;
    
    private int centerIdField;
    
    private OperationStatuses statusField;
    
    private bool statusFieldSpecified;
    
    private bool waitingApprovalField;
    
    /// <remarks/>
    public int ResultCode {
        get {
            return this.resultCodeField;
        }
        set {
            this.resultCodeField = value;
        }
    }
    
    /// <remarks/>
    public long OperationId {
        get {
            return this.operationIdField;
        }
        set {
            this.operationIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ErrorMessage {
        get {
            return this.errorMessageField;
        }
        set {
            this.errorMessageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://data.matrix.financials.fivedegrees.nl/1.0")]
    public ApprovalTypeItem[] Data {
        get {
            return this.dataField;
        }
        set {
            this.dataField = value;
        }
    }
    
    /// <remarks/>
    public int CenterId {
        get {
            return this.centerIdField;
        }
        set {
            this.centerIdField = value;
        }
    }
    
    /// <remarks/>
    public OperationStatuses Status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StatusSpecified {
        get {
            return this.statusFieldSpecified;
        }
        set {
            this.statusFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool WaitingApproval {
        get {
            return this.waitingApprovalField;
        }
        set {
            this.waitingApprovalField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://data.matrix.financials.fivedegrees.nl/1.0")]
public partial class ApprovalTypeItem {
    
    private int idField;
    
    private string nameField;
    
    private string descriptionField;
    
    private int confirmedByCountField;
    
    private OperationTypes[] operationTypesField;
    
    private EntityInfoItem createdField;
    
    private EntityInfoItem changedField;
    
    private string visibilityField;
    
    /// <remarks/>
    public int Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public int ConfirmedByCount {
        get {
            return this.confirmedByCountField;
        }
        set {
            this.confirmedByCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    public OperationTypes[] OperationTypes {
        get {
            return this.operationTypesField;
        }
        set {
            this.operationTypesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public EntityInfoItem Created {
        get {
            return this.createdField;
        }
        set {
            this.createdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public EntityInfoItem Changed {
        get {
            return this.changedField;
        }
        set {
            this.changedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Visibility {
        get {
            return this.visibilityField;
        }
        set {
            this.visibilityField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://data.matrix.financials.fivedegrees.nl/1.0")]
public enum OperationTypes {
    
    /// <remarks/>
    CashAccount_AccountOpen,
    
    /// <remarks/>
    CashAccount_OutgoingPayment,
    
    /// <remarks/>
    CashAccount_ReverseOutgoingPayment,
    
    /// <remarks/>
    CashAccount_IncomingPayment,
    
    /// <remarks/>
    CashAccount_ReverseIncomingPayment,
    
    /// <remarks/>
    CashAccount_GetAccruedInterest,
    
    /// <remarks/>
    CashAccount_ChangeState,
    
    /// <remarks/>
    CashAccount_ReverseChangeState,
    
    /// <remarks/>
    CashAccount_ChargeFee,
    
    /// <remarks/>
    CashAccount_ReverseChargeFee,
    
    /// <remarks/>
    CashAccount_AccrueInterest,
    
    /// <remarks/>
    Core_UnitTest,
    
    /// <remarks/>
    CashAccount_CompoundInterest,
    
    /// <remarks/>
    CashAccount_GetBalance,
    
    /// <remarks/>
    CashAccount_AccountClose,
    
    /// <remarks/>
    ProductBuilder_GetTaxScheme,
    
    /// <remarks/>
    ProductBuilder_GetProducts,
    
    /// <remarks/>
    ProductBuilder_GetTaxSchemes,
    
    /// <remarks/>
    ProductBuilder_GetFeatures,
    
    /// <remarks/>
    ProductBuilder_GetParameters,
    
    /// <remarks/>
    ProductBuilder_GetProduct,
    
    /// <remarks/>
    ProductBuilder_GetInterestSchemes,
    
    /// <remarks/>
    ProductBuilder_CreateProduct,
    
    /// <remarks/>
    ProductBuilder_UpdateProduct,
    
    /// <remarks/>
    ProductBuilder_GetFeature,
    
    /// <remarks/>
    ProductBuilder_GetInterestScheme,
    
    /// <remarks/>
    ProductBuilder_PublishProduct,
    
    /// <remarks/>
    Scheduler_RegisterOneTimeTask,
    
    /// <remarks/>
    Scheduler_RegisterDailyTask,
    
    /// <remarks/>
    Scheduler_RegisterWeeklyTask,
    
    /// <remarks/>
    Scheduler_RegisterMonthlyTask,
    
    /// <remarks/>
    Scheduler_EnableTask,
    
    /// <remarks/>
    Scheduler_DisableTask,
    
    /// <remarks/>
    Scheduler_ExpireTask,
    
    /// <remarks/>
    Scheduler_StatusReport,
    
    /// <remarks/>
    Scheduler_LiveStatusReport,
    
    /// <remarks/>
    Scheduler_GetTask,
    
    /// <remarks/>
    ProductBuilder_GetFeeSchemes,
    
    /// <remarks/>
    CashAccount_AccountDormant,
    
    /// <remarks/>
    CashAccount_AccountFrozen,
    
    /// <remarks/>
    CashAccount_AccountRecycled,
    
    /// <remarks/>
    ProductBuilder_CreateFeeScheme,
    
    /// <remarks/>
    ProductBuilder_CreateTaxScheme,
    
    /// <remarks/>
    ProductBuilder_GetFeeScheme,
    
    /// <remarks/>
    ProductBuilder_CreateInterestScheme,
    
    /// <remarks/>
    Accounting_GetJournalEntries,
    
    /// <remarks/>
    Accounting_GetBalanceSheetEntries,
    
    /// <remarks/>
    Core_EOD,
    
    /// <remarks/>
    Accounting_GetBalanceSheet,
    
    /// <remarks/>
    ProductBuilder_GetTransactionSchemes,
    
    /// <remarks/>
    ProductBuilder_GetTransactionScheme,
    
    /// <remarks/>
    CashAccount_AccountPrepareForClose,
    
    /// <remarks/>
    Core_SetupSystemProductsForCenter,
    
    /// <remarks/>
    Services_GetStatementList,
    
    /// <remarks/>
    Services_GetStatement,
    
    /// <remarks/>
    CashAccount_AccountSweeping,
    
    /// <remarks/>
    CashAccount_ReverseAccountSweeping,
    
    /// <remarks/>
    Payment_CreateIncomingBucket,
    
    /// <remarks/>
    Payment_CreateOutgoingBucket,
    
    /// <remarks/>
    Payment_GetBucketStatus,
    
    /// <remarks/>
    Payment_CancelPaymentsInBucket,
    
    /// <remarks/>
    CashAccount_RevertPayment,
    
    /// <remarks/>
    Operations_RevertOperation,
    
    /// <remarks/>
    Payment_ProcessIncomingPaymentBucket,
    
    /// <remarks/>
    Loan_RegisterRepayment,
    
    /// <remarks/>
    Reversal_Reversible,
    
    /// <remarks/>
    Reversal_CalculateReversal,
    
    /// <remarks/>
    Reversal_Revert,
    
    /// <remarks/>
    ServiceLimits_UpperAgreedFee,
    
    /// <remarks/>
    ServiceLimits_LowerAgreedFee,
    
    /// <remarks/>
    Loan_Close,
    
    /// <remarks/>
    CashAccount_GrantOverdraft,
    
    /// <remarks/>
    Loan_Disburse,
    
    /// <remarks/>
    Loan_Create,
    
    /// <remarks/>
    CashAccount_GetOverdraftLimit,
    
    /// <remarks/>
    CashAccount_GetOverdraftLimits,
    
    /// <remarks/>
    CashAccount_RevokeOverdraft,
    
    /// <remarks/>
    Loan_GetAmountDue,
    
    /// <remarks/>
    Loan_AddAdditionalRepayment,
    
    /// <remarks/>
    Loan_GetLoanStatus,
    
    /// <remarks/>
    ProductBuilder_GetInterestRateSources,
    
    /// <remarks/>
    ProductBuilder_GetServiceLimitInterestRates,
    
    /// <remarks/>
    ProductBuilder_SetServiceLimitInterestRateSources,
    
    /// <remarks/>
    ProductBuilder_CreateTransactionScheme,
    
    /// <remarks/>
    CenterService_CreateCenter,
    
    /// <remarks/>
    CenterService_UpdateCenterEndOfDayTime,
    
    /// <remarks/>
    CenterService_UpdateCenterName,
    
    /// <remarks/>
    CenterService_UpdateCenterBic,
    
    /// <remarks/>
    CenterService_UpdateCenterFallbackAccount,
    
    /// <remarks/>
    CenterService_UpdateCenterErrorAccount,
    
    /// <remarks/>
    CenterService_GetCenterById,
    
    /// <remarks/>
    CenterService_GetCenters,
    
    /// <remarks/>
    CenterService_CreateCenterFromTemplate,
    
    /// <remarks/>
    CenterService_CreateDepartments,
    
    /// <remarks/>
    CenterService_UpdateDepartment,
    
    /// <remarks/>
    CenterService_DeleteDepartment,
    
    /// <remarks/>
    CenterService_GetDepartments,
    
    /// <remarks/>
    CenterService_CreateUnits,
    
    /// <remarks/>
    CenterService_UpdateUnit,
    
    /// <remarks/>
    CenterService_DeleteUnit,
    
    /// <remarks/>
    CenterService_GetUnits,
    
    /// <remarks/>
    CenterService_GetCenterTreeById,
    
    /// <remarks/>
    CenterService_GetCentersTree,
    
    /// <remarks/>
    CenterService_RegisterHolidayCalendar,
    
    /// <remarks/>
    CenterService_DeleteHolidayCalendar,
    
    /// <remarks/>
    CenterService_GetHolidayCalendarsByCenter,
    
    /// <remarks/>
    CenterService_GetHolidayCalendarById,
    
    /// <remarks/>
    CenterService_AddNonBankingDates,
    
    /// <remarks/>
    CenterService_RemoveNonBankingDates,
    
    /// <remarks/>
    CenterService_GetNonBankingDatesByRange,
    
    /// <remarks/>
    ProductBuilder_GetCounterAccounts,
    
    /// <remarks/>
    ProductBuilder_AddServiceBehaviorToProduct,
    
    /// <remarks/>
    ProductBuilder_InsertTransactionBinding,
    
    /// <remarks/>
    ProductBuilder_RemoveTransactionBinding,
    
    /// <remarks/>
    ProductBuilder_RemoveServiceBehaviorFromProduct,
    
    /// <remarks/>
    CenterService_GetCenterUserContext,
    
    /// <remarks/>
    CenterService_SetCenterUserContext,
    
    /// <remarks/>
    Accounting_GetGlAccounts,
    
    /// <remarks/>
    Accounting_CreateGlAccount,
    
    /// <remarks/>
    Accounting_UpdateGlAccount,
    
    /// <remarks/>
    Accounting_DeleteGlAccount,
    
    /// <remarks/>
    ProductBuilder_CreateInterestRateSource,
    
    /// <remarks/>
    ProductBuilder_CreateTaxRateSource,
    
    /// <remarks/>
    ProductBuilder_CreateInterestRate,
    
    /// <remarks/>
    ProductBuilder_CreateTaxRate,
    
    /// <remarks/>
    ProductBuilder_DeleteInterestRateSource,
    
    /// <remarks/>
    ProductBuilder_DeleteTaxRateSource,
    
    /// <remarks/>
    ProductBuilder_GetTaxRateSources,
    
    /// <remarks/>
    Payments_GetPaymentAllocationOrders,
    
    /// <remarks/>
    Payments_GetPaymentAllocationOrderById,
    
    /// <remarks/>
    Payments_CreatePaymentAllocationOrder,
    
    /// <remarks/>
    Payments_DeletePaymentAllocationOrder,
    
    /// <remarks/>
    Payments_UpdatePaymentAllocationOrder,
    
    /// <remarks/>
    ProductBuilder_DiscontinueProduct,
    
    /// <remarks/>
    ProductBuilder_UpdateTaxScheme,
    
    /// <remarks/>
    ProductBuilder_UpdateFeeScheme,
    
    /// <remarks/>
    ProductBuilder_UpdateInterestScheme,
    
    /// <remarks/>
    ProductBuilder_UpdateTransactionScheme,
    
    /// <remarks/>
    ProductBuilder_GetErrorAccounts,
    
    /// <remarks/>
    ProductBuilder_DeleteFeeScheme,
    
    /// <remarks/>
    ProductBuilder_DeleteTaxScheme,
    
    /// <remarks/>
    ProductBuilder_DeleteInterestScheme,
    
    /// <remarks/>
    ProductBuilder_DeleteProduct,
    
    /// <remarks/>
    ProductBuilder_CopyProduct,
    
    /// <remarks/>
    Scheduler_RegisterChainedTask,
    
    /// <remarks/>
    Scheduler_GetTasksByTopic,
    
    /// <remarks/>
    Scheduler_GetRegisteredTopics,
    
    /// <remarks/>
    Scheduler_RegisterTopic,
    
    /// <remarks/>
    Scheduler_IsTopicRegistered,
    
    /// <remarks/>
    Scheduler_ChainTaskToParents,
    
    /// <remarks/>
    Scheduler_UnChainTaskFromParents,
    
    /// <remarks/>
    CenterService_SetupZeroCenter,
    
    /// <remarks/>
    ProductBuilder_CopyProductBetweenCenteres,
    
    /// <remarks/>
    Approvals_GetApprovalTypes,
    
    /// <remarks/>
    Approvals_GetApprovalRequests,
    
    /// <remarks/>
    Approvals_GetApproval,
    
    /// <remarks/>
    Approvals_CreateApprovalType,
    
    /// <remarks/>
    Approvals_DeleteApprovalType,
    
    /// <remarks/>
    Approvals_UpdateApprovalType,
    
    /// <remarks/>
    Approvals_Approve,
    
    /// <remarks/>
    Approvals_Reject,
    
    /// <remarks/>
    Approvals_CreateApprovalRequest,
    
    /// <remarks/>
    Portfolios_GetServices,
    
    /// <remarks/>
    Feature_CashAccount_GetPaymentsOverview,
    
    /// <remarks/>
    Feature_Loan_GetCompleteCashFlow,
    
    /// <remarks/>
    ProductBuilder_GetFeeAccumulativeSettings,
    
    /// <remarks/>
    ProductBuilder_MergeFeeAccumulativeSettings,
    
    /// <remarks/>
    Services_CreateBBANFormat,
    
    /// <remarks/>
    Feature_TermContract_WithdrawalNotice,
    
    /// <remarks/>
    Feature_TermContract_CreateTermContract,
    
    /// <remarks/>
    Feature_TermContract_DepositFromLinkedAccount,
    
    /// <remarks/>
    Services_CreateBBANSequence,
    
    /// <remarks/>
    Services_ConnectProductBBANFormat,
    
    /// <remarks/>
    Feature_TermContract_CloseTermContract,
    
    /// <remarks/>
    ProductBuilder_AddInterestRates,
    
    /// <remarks/>
    Feature_TermContract_EarlyWithdrawal,
    
    /// <remarks/>
    Services_UpdateBBANFormat,
    
    /// <remarks/>
    Services_GetBBANFormat,
    
    /// <remarks/>
    Services_GetBBANFormats,
    
    /// <remarks/>
    Services_UpdateBBANSequence,
    
    /// <remarks/>
    Services_GetBBANSequence,
    
    /// <remarks/>
    Services_GetBBANSequences,
    
    /// <remarks/>
    Services_GetBBANLookupValues,
    
    /// <remarks/>
    Services_UpdateBBANLookupValues,
    
    /// <remarks/>
    Feature_TermContract_CancelWithdrawalNotice,
    
    /// <remarks/>
    Services_GenerateBBANSequenceNumbers,
    
    /// <remarks/>
    Services_GenerateBBAN,
    
    /// <remarks/>
    Services_ConfirmBBANSequence,
    
    /// <remarks/>
    Services_GetBBANSequenceNumbers,
    
    /// <remarks/>
    FX_CreateMultiCurrencyContainer,
    
    /// <remarks/>
    FX_CloseMultiCurrencyContainer,
    
    /// <remarks/>
    FX_CurrencyContainerIncomingPayment,
    
    /// <remarks/>
    FX_CurrencyContainerOutgoingPayment,
    
    /// <remarks/>
    FX_CreateFXSpreadScheme,
    
    /// <remarks/>
    FX_CreateCurrency_pair,
    
    /// <remarks/>
    FX_RegisterReferenceRate,
    
    /// <remarks/>
    Feature_FXSpot_CreateFxSpotContract,
    
    /// <remarks/>
    Feature_FXSpot_IncomingPayment,
    
    /// <remarks/>
    Feature_FXSpot_OutgoingPayment,
    
    /// <remarks/>
    Feature_FXSpot_CloseContract,
    
    /// <remarks/>
    Feature_FXSpot_GetContract,
    
    /// <remarks/>
    Feature_FXSpot_GetContracts,
    
    /// <remarks/>
    FX_CreateFXReferenceRateSource,
    
    /// <remarks/>
    FX_GetMultiCurrencyContainerBalance,
    
    /// <remarks/>
    FX_GetMultiCurrencyContainerMovements,
    
    /// <remarks/>
    Feature_FXSpot_CreateFXQuote,
    
    /// <remarks/>
    Feature_FXSpot_GetFxSpotBalance,
    
    /// <remarks/>
    Feature_FXSpot_GetFxSpotMovements,
    
    /// <remarks/>
    Feature_FXSpot_FXSpotAccountSweep,
    
    /// <remarks/>
    Payment_GetBucket,
    
    /// <remarks/>
    ProductBuilder_GetInterestRates,
    
    /// <remarks/>
    Portfolios_GetService,
    
    /// <remarks/>
    ProductBuilder_GetRelatedFeaturesAndParameters,
    
    /// <remarks/>
    ProductBuilder_CreatePaymentSubtype,
    
    /// <remarks/>
    ProductBuilder_UpdatePaymentSubtype,
    
    /// <remarks/>
    ProductBuilder_DeletePaymentSubtype,
    
    /// <remarks/>
    ProductBuilder_GetPaymentSubtypes,
    
    /// <remarks/>
    Payment_ProcessOutgoingPaymentBucket,
    
    /// <remarks/>
    Payment_ProcessGenericPaymentBucket,
    
    /// <remarks/>
    Feature_CashAccount_GetCashAccountOverview,
    
    /// <remarks/>
    Feature_TermContract_GetTermContractOverview,
    
    /// <remarks/>
    ProductBuilder_GetTaxRates,
    
    /// <remarks/>
    Feature_CashAccount_RegisterInterestRateOverride,
    
    /// <remarks/>
    Feature_CashAccount_CancelInterestRateOverride,
    
    /// <remarks/>
    Feature_CashAccount_DeleteInterestRateOverride,
    
    /// <remarks/>
    Feature_CashAccount_GetInterestRateOverrides,
    
    /// <remarks/>
    FeatureFXSpot_RegisterInterestRateOverride,
    
    /// <remarks/>
    FeatureFXSpot_CancelInterestRateOverride,
    
    /// <remarks/>
    FeatureFXSpot_DeleteInterestRateOverride,
    
    /// <remarks/>
    FeatureFXSpot_GetInterestRateOverrides,
    
    /// <remarks/>
    FeatureTermContract_RegisterInterestRateOverride,
    
    /// <remarks/>
    FeatureTermContract_CancelInterestRateOverride,
    
    /// <remarks/>
    FeatureTermContract_DeleteInterestRateOverride,
    
    /// <remarks/>
    FeatureTermContract_GetInterestRateOverrides,
    
    /// <remarks/>
    FeatureLoan_RegisterInterestRateOverride,
    
    /// <remarks/>
    FeatureLoan_CancelInterestRateOverride,
    
    /// <remarks/>
    FeatureLoan_DeleteInterestRateOverride,
    
    /// <remarks/>
    FeatureLoan_GetInterestRateOverrides,
    
    /// <remarks/>
    FeatureTermContract_EarlyClosure,
    
    /// <remarks/>
    FeatureTermContract_GetPaymentsOverview,
    
    /// <remarks/>
    Core_MigrateMovements,
    
    /// <remarks/>
    FeatureCashAccount_AddNominatedAccount,
    
    /// <remarks/>
    FeatureCashAccount_RemoveNominatedAccount,
    
    /// <remarks/>
    FeatureLoan_AddNominatedAccount,
    
    /// <remarks/>
    FeatureLoan_RemoveNominatedAccount,
    
    /// <remarks/>
    FeatureTermContract_AddNominatedAccount,
    
    /// <remarks/>
    FeatureTermContract_RemoveNominatedAccount,
    
    /// <remarks/>
    FeatureFXSpot_AddNominatedAccount,
    
    /// <remarks/>
    FeatureFXSpot_RemoveNominatedAccount,
    
    /// <remarks/>
    Core_GetPagedMovements,
    
    /// <remarks/>
    Services_ChangeMovementState,
    
    /// <remarks/>
    Accounting_UpdateGlAccountsForServices,
    
    /// <remarks/>
    Payment_CreateIncomingReturnBucket,
    
    /// <remarks/>
    Payment_CreateOutgoingReturnBucket,
    
    /// <remarks/>
    Payment_ReRoutePayment,
    
    /// <remarks/>
    Payment_ReturnPayment,
    
    /// <remarks/>
    Payment_GetBuckets,
    
    /// <remarks/>
    Payments_RegisterMessage,
    
    /// <remarks/>
    Payments_RegisterFileMessage,
    
    /// <remarks/>
    Services_MoveServicesBetweenProducts,
    
    /// <remarks/>
    Payments_Settlements,
    
    /// <remarks/>
    Services_CompoundInterest,
    
    /// <remarks/>
    Services_MoveAllServicesBetweenProducts,
    
    /// <remarks/>
    Payments_MsgId,
    
    /// <remarks/>
    CenterService_GetCenterByBICs,
    
    /// <remarks/>
    Payments_GetMessages,
    
    /// <remarks/>
    Payments_GetMessage,
    
    /// <remarks/>
    Payments_GetMessageFileContent,
    
    /// <remarks/>
    Payments_GetCustomerStatementByMessageId,
    
    /// <remarks/>
    Payments_RegisterCustomerStatement,
    
    /// <remarks/>
    Payments_RegisterMessageBulk,
    
    /// <remarks/>
    Payments_RegisterMessageBulkTransaction,
    
    /// <remarks/>
    Payments_GetOrgnlMessageBulkTransactions,
    
    /// <remarks/>
    Payments_ProcessSettlement,
    
    /// <remarks/>
    CenterService_SetCenterPaymentCutoffTime,
    
    /// <remarks/>
    CenterService_DeleteCenterPaymentCutoffTime,
    
    /// <remarks/>
    Payment_GetBucketsByFilter,
    
    /// <remarks/>
    CenterService_GetCenterPaymentCutoffTime,
    
    /// <remarks/>
    Payments_GetBucketsForExport,
    
    /// <remarks/>
    Payments_MarkBucketsForExport,
    
    /// <remarks/>
    Payments_MarkBucketsForExportCompleted,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://data.matrix.financials.fivedegrees.nl/1.0")]
public partial class EntityInfoItem {
    
    private int userIdField;
    
    private string userNameField;
    
    private System.DateTime eventDateField;
    
    /// <remarks/>
    public int UserId {
        get {
            return this.userIdField;
        }
        set {
            this.userIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string UserName {
        get {
            return this.userNameField;
        }
        set {
            this.userNameField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime EventDate {
        get {
            return this.eventDateField;
        }
        set {
            this.eventDateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:OperationResult")]
public partial class OperationResult_ApprovalStatusItem {
    
    private int resultCodeField;
    
    private long operationIdField;
    
    private string errorMessageField;
    
    private ApprovalStatusItem dataField;
    
    private int centerIdField;
    
    private OperationStatuses statusField;
    
    private bool statusFieldSpecified;
    
    private bool waitingApprovalField;
    
    /// <remarks/>
    public int ResultCode {
        get {
            return this.resultCodeField;
        }
        set {
            this.resultCodeField = value;
        }
    }
    
    /// <remarks/>
    public long OperationId {
        get {
            return this.operationIdField;
        }
        set {
            this.operationIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ErrorMessage {
        get {
            return this.errorMessageField;
        }
        set {
            this.errorMessageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public ApprovalStatusItem Data {
        get {
            return this.dataField;
        }
        set {
            this.dataField = value;
        }
    }
    
    /// <remarks/>
    public int CenterId {
        get {
            return this.centerIdField;
        }
        set {
            this.centerIdField = value;
        }
    }
    
    /// <remarks/>
    public OperationStatuses Status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StatusSpecified {
        get {
            return this.statusFieldSpecified;
        }
        set {
            this.statusFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool WaitingApproval {
        get {
            return this.waitingApprovalField;
        }
        set {
            this.waitingApprovalField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://data.matrix.financials.fivedegrees.nl/1.0")]
public partial class ApprovalStatusItem {
    
    private UserApprovalItem[] approvalItemsField;
    
    private bool hasBeenApprovedField;
    
    private int confirmedByCountField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    public UserApprovalItem[] ApprovalItems {
        get {
            return this.approvalItemsField;
        }
        set {
            this.approvalItemsField = value;
        }
    }
    
    /// <remarks/>
    public bool HasBeenApproved {
        get {
            return this.hasBeenApprovedField;
        }
        set {
            this.hasBeenApprovedField = value;
        }
    }
    
    /// <remarks/>
    public int ConfirmedByCount {
        get {
            return this.confirmedByCountField;
        }
        set {
            this.confirmedByCountField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://data.matrix.financials.fivedegrees.nl/1.0")]
public partial class UserApprovalItem {
    
    private bool isApprovalField;
    
    private string reasonTextField;
    
    private EntityInfoItem createdField;
    
    /// <remarks/>
    public bool IsApproval {
        get {
            return this.isApprovalField;
        }
        set {
            this.isApprovalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ReasonText {
        get {
            return this.reasonTextField;
        }
        set {
            this.reasonTextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public EntityInfoItem Created {
        get {
            return this.createdField;
        }
        set {
            this.createdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://data.matrix.financials.fivedegrees.nl/1.0")]
public enum OperationStatuses {
    
    /// <remarks/>
    Started,
    
    /// <remarks/>
    Completed,
    
    /// <remarks/>
    FunctionalError,
    
    /// <remarks/>
    OperationalError,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:OperationResult")]
public partial class OperationResult_boolean {
    
    private int resultCodeField;
    
    private long operationIdField;
    
    private string errorMessageField;
    
    private bool dataField;
    
    private bool dataFieldSpecified;
    
    private int centerIdField;
    
    private OperationStatuses statusField;
    
    private bool statusFieldSpecified;
    
    private bool waitingApprovalField;
    
    /// <remarks/>
    public int ResultCode {
        get {
            return this.resultCodeField;
        }
        set {
            this.resultCodeField = value;
        }
    }
    
    /// <remarks/>
    public long OperationId {
        get {
            return this.operationIdField;
        }
        set {
            this.operationIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ErrorMessage {
        get {
            return this.errorMessageField;
        }
        set {
            this.errorMessageField = value;
        }
    }
    
    /// <remarks/>
    public bool Data {
        get {
            return this.dataField;
        }
        set {
            this.dataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DataSpecified {
        get {
            return this.dataFieldSpecified;
        }
        set {
            this.dataFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int CenterId {
        get {
            return this.centerIdField;
        }
        set {
            this.centerIdField = value;
        }
    }
    
    /// <remarks/>
    public OperationStatuses Status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StatusSpecified {
        get {
            return this.statusFieldSpecified;
        }
        set {
            this.statusFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool WaitingApproval {
        get {
            return this.waitingApprovalField;
        }
        set {
            this.waitingApprovalField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:OperationResult")]
public partial class OperationResult_int {
    
    private int resultCodeField;
    
    private long operationIdField;
    
    private string errorMessageField;
    
    private int dataField;
    
    private bool dataFieldSpecified;
    
    private int centerIdField;
    
    private OperationStatuses statusField;
    
    private bool statusFieldSpecified;
    
    private bool waitingApprovalField;
    
    /// <remarks/>
    public int ResultCode {
        get {
            return this.resultCodeField;
        }
        set {
            this.resultCodeField = value;
        }
    }
    
    /// <remarks/>
    public long OperationId {
        get {
            return this.operationIdField;
        }
        set {
            this.operationIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ErrorMessage {
        get {
            return this.errorMessageField;
        }
        set {
            this.errorMessageField = value;
        }
    }
    
    /// <remarks/>
    public int Data {
        get {
            return this.dataField;
        }
        set {
            this.dataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DataSpecified {
        get {
            return this.dataFieldSpecified;
        }
        set {
            this.dataFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int CenterId {
        get {
            return this.centerIdField;
        }
        set {
            this.centerIdField = value;
        }
    }
    
    /// <remarks/>
    public OperationStatuses Status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StatusSpecified {
        get {
            return this.statusFieldSpecified;
        }
        set {
            this.statusFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool WaitingApproval {
        get {
            return this.waitingApprovalField;
        }
        set {
            this.waitingApprovalField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(UpdateApprovalTypeItem))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://data.matrix.financials.fivedegrees.nl/1.0")]
public partial class CreateApprovalTypeItem {
    
    private string nameField;
    
    private string descriptionField;
    
    private int confirmedByCountField;
    
    private string visibilityField;
    
    private OperationTypes[] operationTypesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public int ConfirmedByCount {
        get {
            return this.confirmedByCountField;
        }
        set {
            this.confirmedByCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Visibility {
        get {
            return this.visibilityField;
        }
        set {
            this.visibilityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    public OperationTypes[] OperationTypes {
        get {
            return this.operationTypesField;
        }
        set {
            this.operationTypesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://data.matrix.financials.fivedegrees.nl/1.0")]
public partial class UpdateApprovalTypeItem : CreateApprovalTypeItem {
    
    private int idField;
    
    /// <remarks/>
    public int Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:OperationResult")]
public partial class OperationResult_ApprovalRequestItem {
    
    private int resultCodeField;
    
    private long operationIdField;
    
    private string errorMessageField;
    
    private ApprovalRequestItem dataField;
    
    private int centerIdField;
    
    private OperationStatuses statusField;
    
    private bool statusFieldSpecified;
    
    private bool waitingApprovalField;
    
    /// <remarks/>
    public int ResultCode {
        get {
            return this.resultCodeField;
        }
        set {
            this.resultCodeField = value;
        }
    }
    
    /// <remarks/>
    public long OperationId {
        get {
            return this.operationIdField;
        }
        set {
            this.operationIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ErrorMessage {
        get {
            return this.errorMessageField;
        }
        set {
            this.errorMessageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public ApprovalRequestItem Data {
        get {
            return this.dataField;
        }
        set {
            this.dataField = value;
        }
    }
    
    /// <remarks/>
    public int CenterId {
        get {
            return this.centerIdField;
        }
        set {
            this.centerIdField = value;
        }
    }
    
    /// <remarks/>
    public OperationStatuses Status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StatusSpecified {
        get {
            return this.statusFieldSpecified;
        }
        set {
            this.statusFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool WaitingApproval {
        get {
            return this.waitingApprovalField;
        }
        set {
            this.waitingApprovalField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://data.matrix.financials.fivedegrees.nl/1.0")]
public partial class ApprovalRequestItem {
    
    private string idField;
    
    private long transactionIdField;
    
    private int approvalTypeIdField;
    
    private OperationTypes operationTypeField;
    
    private ApprovalStates approvalStateField;
    
    private EntityInfoItem createdField;
    
    private EntityInfoItem changedField;
    
    private ApprovalStatusItem approvalHistoryField;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public long TransactionId {
        get {
            return this.transactionIdField;
        }
        set {
            this.transactionIdField = value;
        }
    }
    
    /// <remarks/>
    public int ApprovalTypeId {
        get {
            return this.approvalTypeIdField;
        }
        set {
            this.approvalTypeIdField = value;
        }
    }
    
    /// <remarks/>
    public OperationTypes OperationType {
        get {
            return this.operationTypeField;
        }
        set {
            this.operationTypeField = value;
        }
    }
    
    /// <remarks/>
    public ApprovalStates ApprovalState {
        get {
            return this.approvalStateField;
        }
        set {
            this.approvalStateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public EntityInfoItem Created {
        get {
            return this.createdField;
        }
        set {
            this.createdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public EntityInfoItem Changed {
        get {
            return this.changedField;
        }
        set {
            this.changedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public ApprovalStatusItem ApprovalHistory {
        get {
            return this.approvalHistoryField;
        }
        set {
            this.approvalHistoryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://data.matrix.financials.fivedegrees.nl/1.0")]
public enum ApprovalStates {
    
    /// <remarks/>
    Created,
    
    /// <remarks/>
    Waiting,
    
    /// <remarks/>
    Approved,
    
    /// <remarks/>
    Processed,
    
    /// <remarks/>
    Rejected,
    
    /// <remarks/>
    Error,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:OperationResult")]
public partial class OperationResult_ArrayOfApprovalRequestItem {
    
    private int resultCodeField;
    
    private long operationIdField;
    
    private string errorMessageField;
    
    private ApprovalRequestItem[] dataField;
    
    private int centerIdField;
    
    private OperationStatuses statusField;
    
    private bool statusFieldSpecified;
    
    private bool waitingApprovalField;
    
    /// <remarks/>
    public int ResultCode {
        get {
            return this.resultCodeField;
        }
        set {
            this.resultCodeField = value;
        }
    }
    
    /// <remarks/>
    public long OperationId {
        get {
            return this.operationIdField;
        }
        set {
            this.operationIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ErrorMessage {
        get {
            return this.errorMessageField;
        }
        set {
            this.errorMessageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://data.matrix.financials.fivedegrees.nl/1.0")]
    public ApprovalRequestItem[] Data {
        get {
            return this.dataField;
        }
        set {
            this.dataField = value;
        }
    }
    
    /// <remarks/>
    public int CenterId {
        get {
            return this.centerIdField;
        }
        set {
            this.centerIdField = value;
        }
    }
    
    /// <remarks/>
    public OperationStatuses Status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StatusSpecified {
        get {
            return this.statusFieldSpecified;
        }
        set {
            this.statusFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool WaitingApproval {
        get {
            return this.waitingApprovalField;
        }
        set {
            this.waitingApprovalField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void GetApprovalTypesCompletedEventHandler(object sender, GetApprovalTypesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetApprovalTypesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetApprovalTypesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public OperationResult_ArrayOfApprovalTypeItem Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((OperationResult_ArrayOfApprovalTypeItem)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void GetApprovalRequestsCompletedEventHandler(object sender, GetApprovalRequestsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetApprovalRequestsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetApprovalRequestsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public OperationResult_ArrayOfApprovalRequestItem Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((OperationResult_ArrayOfApprovalRequestItem)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void GetApprovalCompletedEventHandler(object sender, GetApprovalCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetApprovalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetApprovalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public OperationResult_ApprovalRequestItem Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((OperationResult_ApprovalRequestItem)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void CreateApprovalTypeCompletedEventHandler(object sender, CreateApprovalTypeCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CreateApprovalTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal CreateApprovalTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public OperationResult_int Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((OperationResult_int)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void DeleteApprovalTypeCompletedEventHandler(object sender, DeleteApprovalTypeCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class DeleteApprovalTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal DeleteApprovalTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public OperationResult_boolean Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((OperationResult_boolean)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void UpdateApprovalTypeCompletedEventHandler(object sender, UpdateApprovalTypeCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class UpdateApprovalTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal UpdateApprovalTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public OperationResult_boolean Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((OperationResult_boolean)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void ApproveCompletedEventHandler(object sender, ApproveCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ApproveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal ApproveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public OperationResult_ApprovalStatusItem Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((OperationResult_ApprovalStatusItem)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void RejectCompletedEventHandler(object sender, RejectCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class RejectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal RejectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public OperationResult_ApprovalStatusItem Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((OperationResult_ApprovalStatusItem)(this.results[0]));
        }
    }
}
