//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.33440.
// 


/// <remarks/>
// CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="IAccountingService_Endpoint", Namespace="http://service.matrix.financials.fivedegrees.nl/1.0")]
public partial class AccountingServiceBSL : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback CheckOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetJournalEntriesOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetBalanceSheetEntriesOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetBalanceSheetOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetGlAccountsOperationCompleted;
    
    private System.Threading.SendOrPostCallback CreateGlAccountOperationCompleted;
    
    private System.Threading.SendOrPostCallback UpdateGlAccountOperationCompleted;
    
    private System.Threading.SendOrPostCallback DeleteGlAccountOperationCompleted;
    
    private System.Threading.SendOrPostCallback UpdateGlAccountsForServicesOperationCompleted;
    
    /// <remarks/>
    public AccountingServiceBSL() {
        this.Url = "https://localhost:44303/Service.svc";
    }
    
    /// <remarks/>
    public event CheckCompletedEventHandler CheckCompleted;
    
    /// <remarks/>
    public event GetJournalEntriesCompletedEventHandler GetJournalEntriesCompleted;
    
    /// <remarks/>
    public event GetBalanceSheetEntriesCompletedEventHandler GetBalanceSheetEntriesCompleted;
    
    /// <remarks/>
    public event GetBalanceSheetCompletedEventHandler GetBalanceSheetCompleted;
    
    /// <remarks/>
    public event GetGlAccountsCompletedEventHandler GetGlAccountsCompleted;
    
    /// <remarks/>
    public event CreateGlAccountCompletedEventHandler CreateGlAccountCompleted;
    
    /// <remarks/>
    public event UpdateGlAccountCompletedEventHandler UpdateGlAccountCompleted;
    
    /// <remarks/>
    public event DeleteGlAccountCompletedEventHandler DeleteGlAccountCompleted;
    
    /// <remarks/>
    public event UpdateGlAccountsForServicesCompletedEventHandler UpdateGlAccountsForServicesCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.matrix.financials.fivedegrees.nl/1.0/IHealthCheckService/Check", RequestNamespace="http://service.matrix.financials.fivedegrees.nl/1.0", ResponseNamespace="http://service.matrix.financials.fivedegrees.nl/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public HealthCheckItem Check() {
        object[] results = this.Invoke("Check", new object[0]);
        return ((HealthCheckItem)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginCheck(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Check", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public HealthCheckItem EndCheck(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((HealthCheckItem)(results[0]));
    }
    
    /// <remarks/>
    public void CheckAsync() {
        this.CheckAsync(null);
    }
    
    /// <remarks/>
    public void CheckAsync(object userState) {
        if ((this.CheckOperationCompleted == null)) {
            this.CheckOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckOperationCompleted);
        }
        this.InvokeAsync("Check", new object[0], this.CheckOperationCompleted, userState);
    }
    
    private void OnCheckOperationCompleted(object arg) {
        if ((this.CheckCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.CheckCompleted(this, new CheckCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.matrix.financials.fivedegrees.nl/1.0/IAccountingService/GetJournal" +
        "Entries", RequestNamespace="http://service.matrix.financials.fivedegrees.nl/1.0", ResponseNamespace="http://service.matrix.financials.fivedegrees.nl/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public OperationResult_ArrayOfJournalEntryListItem GetJournalEntries(string correlationId, int centerId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool centerIdSpecified, System.DateTime startDate, [System.Xml.Serialization.XmlIgnoreAttribute()] bool startDateSpecified, System.DateTime endDate, [System.Xml.Serialization.XmlIgnoreAttribute()] bool endDateSpecified) {
        object[] results = this.Invoke("GetJournalEntries", new object[] {
                    correlationId,
                    centerId,
                    centerIdSpecified,
                    startDate,
                    startDateSpecified,
                    endDate,
                    endDateSpecified});
        return ((OperationResult_ArrayOfJournalEntryListItem)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetJournalEntries(string correlationId, int centerId, bool centerIdSpecified, System.DateTime startDate, bool startDateSpecified, System.DateTime endDate, bool endDateSpecified, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetJournalEntries", new object[] {
                    correlationId,
                    centerId,
                    centerIdSpecified,
                    startDate,
                    startDateSpecified,
                    endDate,
                    endDateSpecified}, callback, asyncState);
    }
    
    /// <remarks/>
    public OperationResult_ArrayOfJournalEntryListItem EndGetJournalEntries(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((OperationResult_ArrayOfJournalEntryListItem)(results[0]));
    }
    
    /// <remarks/>
    public void GetJournalEntriesAsync(string correlationId, int centerId, bool centerIdSpecified, System.DateTime startDate, bool startDateSpecified, System.DateTime endDate, bool endDateSpecified) {
        this.GetJournalEntriesAsync(correlationId, centerId, centerIdSpecified, startDate, startDateSpecified, endDate, endDateSpecified, null);
    }
    
    /// <remarks/>
    public void GetJournalEntriesAsync(string correlationId, int centerId, bool centerIdSpecified, System.DateTime startDate, bool startDateSpecified, System.DateTime endDate, bool endDateSpecified, object userState) {
        if ((this.GetJournalEntriesOperationCompleted == null)) {
            this.GetJournalEntriesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetJournalEntriesOperationCompleted);
        }
        this.InvokeAsync("GetJournalEntries", new object[] {
                    correlationId,
                    centerId,
                    centerIdSpecified,
                    startDate,
                    startDateSpecified,
                    endDate,
                    endDateSpecified}, this.GetJournalEntriesOperationCompleted, userState);
    }
    
    private void OnGetJournalEntriesOperationCompleted(object arg) {
        if ((this.GetJournalEntriesCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetJournalEntriesCompleted(this, new GetJournalEntriesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.matrix.financials.fivedegrees.nl/1.0/IAccountingService/GetBalance" +
        "SheetEntries", RequestNamespace="http://service.matrix.financials.fivedegrees.nl/1.0", ResponseNamespace="http://service.matrix.financials.fivedegrees.nl/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public OperationResult_ArrayOfBalanceSheetEntryListItem GetBalanceSheetEntries(string correlationId, int centerId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool centerIdSpecified, System.DateTime date, [System.Xml.Serialization.XmlIgnoreAttribute()] bool dateSpecified) {
        object[] results = this.Invoke("GetBalanceSheetEntries", new object[] {
                    correlationId,
                    centerId,
                    centerIdSpecified,
                    date,
                    dateSpecified});
        return ((OperationResult_ArrayOfBalanceSheetEntryListItem)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetBalanceSheetEntries(string correlationId, int centerId, bool centerIdSpecified, System.DateTime date, bool dateSpecified, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetBalanceSheetEntries", new object[] {
                    correlationId,
                    centerId,
                    centerIdSpecified,
                    date,
                    dateSpecified}, callback, asyncState);
    }
    
    /// <remarks/>
    public OperationResult_ArrayOfBalanceSheetEntryListItem EndGetBalanceSheetEntries(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((OperationResult_ArrayOfBalanceSheetEntryListItem)(results[0]));
    }
    
    /// <remarks/>
    public void GetBalanceSheetEntriesAsync(string correlationId, int centerId, bool centerIdSpecified, System.DateTime date, bool dateSpecified) {
        this.GetBalanceSheetEntriesAsync(correlationId, centerId, centerIdSpecified, date, dateSpecified, null);
    }
    
    /// <remarks/>
    public void GetBalanceSheetEntriesAsync(string correlationId, int centerId, bool centerIdSpecified, System.DateTime date, bool dateSpecified, object userState) {
        if ((this.GetBalanceSheetEntriesOperationCompleted == null)) {
            this.GetBalanceSheetEntriesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBalanceSheetEntriesOperationCompleted);
        }
        this.InvokeAsync("GetBalanceSheetEntries", new object[] {
                    correlationId,
                    centerId,
                    centerIdSpecified,
                    date,
                    dateSpecified}, this.GetBalanceSheetEntriesOperationCompleted, userState);
    }
    
    private void OnGetBalanceSheetEntriesOperationCompleted(object arg) {
        if ((this.GetBalanceSheetEntriesCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetBalanceSheetEntriesCompleted(this, new GetBalanceSheetEntriesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.matrix.financials.fivedegrees.nl/1.0/IAccountingService/GetBalance" +
        "Sheet", RequestNamespace="http://service.matrix.financials.fivedegrees.nl/1.0", ResponseNamespace="http://service.matrix.financials.fivedegrees.nl/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public OperationResult_ArrayOfBalanceSheetListItem GetBalanceSheet(string correlationId, int centerId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool centerIdSpecified, System.DateTime date, [System.Xml.Serialization.XmlIgnoreAttribute()] bool dateSpecified, BalanceSheetEntryTypes balanceSheetEntryType, [System.Xml.Serialization.XmlIgnoreAttribute()] bool balanceSheetEntryTypeSpecified) {
        object[] results = this.Invoke("GetBalanceSheet", new object[] {
                    correlationId,
                    centerId,
                    centerIdSpecified,
                    date,
                    dateSpecified,
                    balanceSheetEntryType,
                    balanceSheetEntryTypeSpecified});
        return ((OperationResult_ArrayOfBalanceSheetListItem)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetBalanceSheet(string correlationId, int centerId, bool centerIdSpecified, System.DateTime date, bool dateSpecified, BalanceSheetEntryTypes balanceSheetEntryType, bool balanceSheetEntryTypeSpecified, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetBalanceSheet", new object[] {
                    correlationId,
                    centerId,
                    centerIdSpecified,
                    date,
                    dateSpecified,
                    balanceSheetEntryType,
                    balanceSheetEntryTypeSpecified}, callback, asyncState);
    }
    
    /// <remarks/>
    public OperationResult_ArrayOfBalanceSheetListItem EndGetBalanceSheet(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((OperationResult_ArrayOfBalanceSheetListItem)(results[0]));
    }
    
    /// <remarks/>
    public void GetBalanceSheetAsync(string correlationId, int centerId, bool centerIdSpecified, System.DateTime date, bool dateSpecified, BalanceSheetEntryTypes balanceSheetEntryType, bool balanceSheetEntryTypeSpecified) {
        this.GetBalanceSheetAsync(correlationId, centerId, centerIdSpecified, date, dateSpecified, balanceSheetEntryType, balanceSheetEntryTypeSpecified, null);
    }
    
    /// <remarks/>
    public void GetBalanceSheetAsync(string correlationId, int centerId, bool centerIdSpecified, System.DateTime date, bool dateSpecified, BalanceSheetEntryTypes balanceSheetEntryType, bool balanceSheetEntryTypeSpecified, object userState) {
        if ((this.GetBalanceSheetOperationCompleted == null)) {
            this.GetBalanceSheetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBalanceSheetOperationCompleted);
        }
        this.InvokeAsync("GetBalanceSheet", new object[] {
                    correlationId,
                    centerId,
                    centerIdSpecified,
                    date,
                    dateSpecified,
                    balanceSheetEntryType,
                    balanceSheetEntryTypeSpecified}, this.GetBalanceSheetOperationCompleted, userState);
    }
    
    private void OnGetBalanceSheetOperationCompleted(object arg) {
        if ((this.GetBalanceSheetCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetBalanceSheetCompleted(this, new GetBalanceSheetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.matrix.financials.fivedegrees.nl/1.0/IAccountingService/GetGlAccou" +
        "nts", RequestNamespace="http://service.matrix.financials.fivedegrees.nl/1.0", ResponseNamespace="http://service.matrix.financials.fivedegrees.nl/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public OperationResult_ArrayOfGlAccountItem GetGlAccounts(string correlationId, int centerId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool centerIdSpecified) {
        object[] results = this.Invoke("GetGlAccounts", new object[] {
                    correlationId,
                    centerId,
                    centerIdSpecified});
        return ((OperationResult_ArrayOfGlAccountItem)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetGlAccounts(string correlationId, int centerId, bool centerIdSpecified, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetGlAccounts", new object[] {
                    correlationId,
                    centerId,
                    centerIdSpecified}, callback, asyncState);
    }
    
    /// <remarks/>
    public OperationResult_ArrayOfGlAccountItem EndGetGlAccounts(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((OperationResult_ArrayOfGlAccountItem)(results[0]));
    }
    
    /// <remarks/>
    public void GetGlAccountsAsync(string correlationId, int centerId, bool centerIdSpecified) {
        this.GetGlAccountsAsync(correlationId, centerId, centerIdSpecified, null);
    }
    
    /// <remarks/>
    public void GetGlAccountsAsync(string correlationId, int centerId, bool centerIdSpecified, object userState) {
        if ((this.GetGlAccountsOperationCompleted == null)) {
            this.GetGlAccountsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGlAccountsOperationCompleted);
        }
        this.InvokeAsync("GetGlAccounts", new object[] {
                    correlationId,
                    centerId,
                    centerIdSpecified}, this.GetGlAccountsOperationCompleted, userState);
    }
    
    private void OnGetGlAccountsOperationCompleted(object arg) {
        if ((this.GetGlAccountsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetGlAccountsCompleted(this, new GetGlAccountsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.matrix.financials.fivedegrees.nl/1.0/IAccountingService/CreateGlAc" +
        "count", RequestNamespace="http://service.matrix.financials.fivedegrees.nl/1.0", ResponseNamespace="http://service.matrix.financials.fivedegrees.nl/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public OperationResult_int CreateGlAccount(string correlationId, int centerId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool centerIdSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] CreateGlAccountItem glAccountItem) {
        object[] results = this.Invoke("CreateGlAccount", new object[] {
                    correlationId,
                    centerId,
                    centerIdSpecified,
                    glAccountItem});
        return ((OperationResult_int)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginCreateGlAccount(string correlationId, int centerId, bool centerIdSpecified, CreateGlAccountItem glAccountItem, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("CreateGlAccount", new object[] {
                    correlationId,
                    centerId,
                    centerIdSpecified,
                    glAccountItem}, callback, asyncState);
    }
    
    /// <remarks/>
    public OperationResult_int EndCreateGlAccount(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((OperationResult_int)(results[0]));
    }
    
    /// <remarks/>
    public void CreateGlAccountAsync(string correlationId, int centerId, bool centerIdSpecified, CreateGlAccountItem glAccountItem) {
        this.CreateGlAccountAsync(correlationId, centerId, centerIdSpecified, glAccountItem, null);
    }
    
    /// <remarks/>
    public void CreateGlAccountAsync(string correlationId, int centerId, bool centerIdSpecified, CreateGlAccountItem glAccountItem, object userState) {
        if ((this.CreateGlAccountOperationCompleted == null)) {
            this.CreateGlAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateGlAccountOperationCompleted);
        }
        this.InvokeAsync("CreateGlAccount", new object[] {
                    correlationId,
                    centerId,
                    centerIdSpecified,
                    glAccountItem}, this.CreateGlAccountOperationCompleted, userState);
    }
    
    private void OnCreateGlAccountOperationCompleted(object arg) {
        if ((this.CreateGlAccountCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.CreateGlAccountCompleted(this, new CreateGlAccountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.matrix.financials.fivedegrees.nl/1.0/IAccountingService/UpdateGlAc" +
        "count", RequestNamespace="http://service.matrix.financials.fivedegrees.nl/1.0", ResponseNamespace="http://service.matrix.financials.fivedegrees.nl/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public OperationResult_boolean UpdateGlAccount(string correlationId, int centerId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool centerIdSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] UpdateGlAccountItem updateGlAccountItem) {
        object[] results = this.Invoke("UpdateGlAccount", new object[] {
                    correlationId,
                    centerId,
                    centerIdSpecified,
                    updateGlAccountItem});
        return ((OperationResult_boolean)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginUpdateGlAccount(string correlationId, int centerId, bool centerIdSpecified, UpdateGlAccountItem updateGlAccountItem, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("UpdateGlAccount", new object[] {
                    correlationId,
                    centerId,
                    centerIdSpecified,
                    updateGlAccountItem}, callback, asyncState);
    }
    
    /// <remarks/>
    public OperationResult_boolean EndUpdateGlAccount(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((OperationResult_boolean)(results[0]));
    }
    
    /// <remarks/>
    public void UpdateGlAccountAsync(string correlationId, int centerId, bool centerIdSpecified, UpdateGlAccountItem updateGlAccountItem) {
        this.UpdateGlAccountAsync(correlationId, centerId, centerIdSpecified, updateGlAccountItem, null);
    }
    
    /// <remarks/>
    public void UpdateGlAccountAsync(string correlationId, int centerId, bool centerIdSpecified, UpdateGlAccountItem updateGlAccountItem, object userState) {
        if ((this.UpdateGlAccountOperationCompleted == null)) {
            this.UpdateGlAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateGlAccountOperationCompleted);
        }
        this.InvokeAsync("UpdateGlAccount", new object[] {
                    correlationId,
                    centerId,
                    centerIdSpecified,
                    updateGlAccountItem}, this.UpdateGlAccountOperationCompleted, userState);
    }
    
    private void OnUpdateGlAccountOperationCompleted(object arg) {
        if ((this.UpdateGlAccountCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.UpdateGlAccountCompleted(this, new UpdateGlAccountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.matrix.financials.fivedegrees.nl/1.0/IAccountingService/DeleteGlAc" +
        "count", RequestNamespace="http://service.matrix.financials.fivedegrees.nl/1.0", ResponseNamespace="http://service.matrix.financials.fivedegrees.nl/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public OperationResult_boolean DeleteGlAccount(string correlationId, int centerId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool centerIdSpecified, int glAccountId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool glAccountIdSpecified) {
        object[] results = this.Invoke("DeleteGlAccount", new object[] {
                    correlationId,
                    centerId,
                    centerIdSpecified,
                    glAccountId,
                    glAccountIdSpecified});
        return ((OperationResult_boolean)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginDeleteGlAccount(string correlationId, int centerId, bool centerIdSpecified, int glAccountId, bool glAccountIdSpecified, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("DeleteGlAccount", new object[] {
                    correlationId,
                    centerId,
                    centerIdSpecified,
                    glAccountId,
                    glAccountIdSpecified}, callback, asyncState);
    }
    
    /// <remarks/>
    public OperationResult_boolean EndDeleteGlAccount(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((OperationResult_boolean)(results[0]));
    }
    
    /// <remarks/>
    public void DeleteGlAccountAsync(string correlationId, int centerId, bool centerIdSpecified, int glAccountId, bool glAccountIdSpecified) {
        this.DeleteGlAccountAsync(correlationId, centerId, centerIdSpecified, glAccountId, glAccountIdSpecified, null);
    }
    
    /// <remarks/>
    public void DeleteGlAccountAsync(string correlationId, int centerId, bool centerIdSpecified, int glAccountId, bool glAccountIdSpecified, object userState) {
        if ((this.DeleteGlAccountOperationCompleted == null)) {
            this.DeleteGlAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteGlAccountOperationCompleted);
        }
        this.InvokeAsync("DeleteGlAccount", new object[] {
                    correlationId,
                    centerId,
                    centerIdSpecified,
                    glAccountId,
                    glAccountIdSpecified}, this.DeleteGlAccountOperationCompleted, userState);
    }
    
    private void OnDeleteGlAccountOperationCompleted(object arg) {
        if ((this.DeleteGlAccountCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.DeleteGlAccountCompleted(this, new DeleteGlAccountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.matrix.financials.fivedegrees.nl/1.0/IAccountingService/UpdateGlAc" +
        "countsForServices", RequestNamespace="http://service.matrix.financials.fivedegrees.nl/1.0", ResponseNamespace="http://service.matrix.financials.fivedegrees.nl/1.0", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public OperationResult_boolean UpdateGlAccountsForServices(string correlationId, int centerId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool centerIdSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> glAccountId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool glAccountIdSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> accruedInterestGlAccountId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool accruedInterestGlAccountIdSpecified, [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")] string[] accountNumbers) {
        object[] results = this.Invoke("UpdateGlAccountsForServices", new object[] {
                    correlationId,
                    centerId,
                    centerIdSpecified,
                    glAccountId,
                    glAccountIdSpecified,
                    accruedInterestGlAccountId,
                    accruedInterestGlAccountIdSpecified,
                    accountNumbers});
        return ((OperationResult_boolean)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginUpdateGlAccountsForServices(string correlationId, int centerId, bool centerIdSpecified, System.Nullable<int> glAccountId, bool glAccountIdSpecified, System.Nullable<int> accruedInterestGlAccountId, bool accruedInterestGlAccountIdSpecified, string[] accountNumbers, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("UpdateGlAccountsForServices", new object[] {
                    correlationId,
                    centerId,
                    centerIdSpecified,
                    glAccountId,
                    glAccountIdSpecified,
                    accruedInterestGlAccountId,
                    accruedInterestGlAccountIdSpecified,
                    accountNumbers}, callback, asyncState);
    }
    
    /// <remarks/>
    public OperationResult_boolean EndUpdateGlAccountsForServices(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((OperationResult_boolean)(results[0]));
    }
    
    /// <remarks/>
    public void UpdateGlAccountsForServicesAsync(string correlationId, int centerId, bool centerIdSpecified, System.Nullable<int> glAccountId, bool glAccountIdSpecified, System.Nullable<int> accruedInterestGlAccountId, bool accruedInterestGlAccountIdSpecified, string[] accountNumbers) {
        this.UpdateGlAccountsForServicesAsync(correlationId, centerId, centerIdSpecified, glAccountId, glAccountIdSpecified, accruedInterestGlAccountId, accruedInterestGlAccountIdSpecified, accountNumbers, null);
    }
    
    /// <remarks/>
    public void UpdateGlAccountsForServicesAsync(string correlationId, int centerId, bool centerIdSpecified, System.Nullable<int> glAccountId, bool glAccountIdSpecified, System.Nullable<int> accruedInterestGlAccountId, bool accruedInterestGlAccountIdSpecified, string[] accountNumbers, object userState) {
        if ((this.UpdateGlAccountsForServicesOperationCompleted == null)) {
            this.UpdateGlAccountsForServicesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateGlAccountsForServicesOperationCompleted);
        }
        this.InvokeAsync("UpdateGlAccountsForServices", new object[] {
                    correlationId,
                    centerId,
                    centerIdSpecified,
                    glAccountId,
                    glAccountIdSpecified,
                    accruedInterestGlAccountId,
                    accruedInterestGlAccountIdSpecified,
                    accountNumbers}, this.UpdateGlAccountsForServicesOperationCompleted, userState);
    }
    
    private void OnUpdateGlAccountsForServicesOperationCompleted(object arg) {
        if ((this.UpdateGlAccountsForServicesCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.UpdateGlAccountsForServicesCompleted(this, new UpdateGlAccountsForServicesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:OperationResult")]
public partial class HealthCheckItem {
    
    private bool okField;
    
    private string serviceNameField;
    
    private System.DateTime databaseTimeField;
    
    private System.DateTime serverTimeField;
    
    /// <remarks/>
    public bool Ok {
        get {
            return this.okField;
        }
        set {
            this.okField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ServiceName {
        get {
            return this.serviceNameField;
        }
        set {
            this.serviceNameField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime DatabaseTime {
        get {
            return this.databaseTimeField;
        }
        set {
            this.databaseTimeField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime ServerTime {
        get {
            return this.serverTimeField;
        }
        set {
            this.serverTimeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:OperationResult")]
public partial class OperationResult_boolean {
    
    private int resultCodeField;
    
    private long operationIdField;
    
    private string errorMessageField;
    
    private bool dataField;
    
    private bool dataFieldSpecified;
    
    private int centerIdField;
    
    private OperationStatuses statusField;
    
    private bool statusFieldSpecified;
    
    private bool waitingApprovalField;
    
    /// <remarks/>
    public int ResultCode {
        get {
            return this.resultCodeField;
        }
        set {
            this.resultCodeField = value;
        }
    }
    
    /// <remarks/>
    public long OperationId {
        get {
            return this.operationIdField;
        }
        set {
            this.operationIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ErrorMessage {
        get {
            return this.errorMessageField;
        }
        set {
            this.errorMessageField = value;
        }
    }
    
    /// <remarks/>
    public bool Data {
        get {
            return this.dataField;
        }
        set {
            this.dataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DataSpecified {
        get {
            return this.dataFieldSpecified;
        }
        set {
            this.dataFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int CenterId {
        get {
            return this.centerIdField;
        }
        set {
            this.centerIdField = value;
        }
    }
    
    /// <remarks/>
    public OperationStatuses Status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StatusSpecified {
        get {
            return this.statusFieldSpecified;
        }
        set {
            this.statusFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool WaitingApproval {
        get {
            return this.waitingApprovalField;
        }
        set {
            this.waitingApprovalField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://data.matrix.financials.fivedegrees.nl/1.0")]
public enum OperationStatuses {
    
    /// <remarks/>
    Started,
    
    /// <remarks/>
    Completed,
    
    /// <remarks/>
    FunctionalError,
    
    /// <remarks/>
    OperationalError,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:OperationResult")]
public partial class OperationResult_int {
    
    private int resultCodeField;
    
    private long operationIdField;
    
    private string errorMessageField;
    
    private int dataField;
    
    private bool dataFieldSpecified;
    
    private int centerIdField;
    
    private OperationStatuses statusField;
    
    private bool statusFieldSpecified;
    
    private bool waitingApprovalField;
    
    /// <remarks/>
    public int ResultCode {
        get {
            return this.resultCodeField;
        }
        set {
            this.resultCodeField = value;
        }
    }
    
    /// <remarks/>
    public long OperationId {
        get {
            return this.operationIdField;
        }
        set {
            this.operationIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ErrorMessage {
        get {
            return this.errorMessageField;
        }
        set {
            this.errorMessageField = value;
        }
    }
    
    /// <remarks/>
    public int Data {
        get {
            return this.dataField;
        }
        set {
            this.dataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DataSpecified {
        get {
            return this.dataFieldSpecified;
        }
        set {
            this.dataFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int CenterId {
        get {
            return this.centerIdField;
        }
        set {
            this.centerIdField = value;
        }
    }
    
    /// <remarks/>
    public OperationStatuses Status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StatusSpecified {
        get {
            return this.statusFieldSpecified;
        }
        set {
            this.statusFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool WaitingApproval {
        get {
            return this.waitingApprovalField;
        }
        set {
            this.waitingApprovalField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(UpdateGlAccountItem))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://data.matrix.financials.fivedegrees.nl/1.0")]
public partial class CreateGlAccountItem {
    
    private string accountNameField;
    
    private string descriptionField;
    
    private System.Nullable<GlAccountTypes> glAccountTypeField;
    
    private bool glAccountTypeFieldSpecified;
    
    private string externalAccountField;
    
    private System.Nullable<GlAccountsMappingRules> glAccountsMappingRuleField;
    
    private bool glAccountsMappingRuleFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string AccountName {
        get {
            return this.accountNameField;
        }
        set {
            this.accountNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<GlAccountTypes> GlAccountType {
        get {
            return this.glAccountTypeField;
        }
        set {
            this.glAccountTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool GlAccountTypeSpecified {
        get {
            return this.glAccountTypeFieldSpecified;
        }
        set {
            this.glAccountTypeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ExternalAccount {
        get {
            return this.externalAccountField;
        }
        set {
            this.externalAccountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<GlAccountsMappingRules> GlAccountsMappingRule {
        get {
            return this.glAccountsMappingRuleField;
        }
        set {
            this.glAccountsMappingRuleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool GlAccountsMappingRuleSpecified {
        get {
            return this.glAccountsMappingRuleFieldSpecified;
        }
        set {
            this.glAccountsMappingRuleFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://data.matrix.financials.fivedegrees.nl/1.0")]
public enum GlAccountTypes {
    
    /// <remarks/>
    BalanceSheet,
    
    /// <remarks/>
    IncomeStatement,
    
    /// <remarks/>
    Equity,
    
    /// <remarks/>
    InterestAccruals,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://data.matrix.financials.fivedegrees.nl/1.0")]
public enum GlAccountsMappingRules {
    
    /// <remarks/>
    PositiveToCredit,
    
    /// <remarks/>
    PositiveToDebit,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://data.matrix.financials.fivedegrees.nl/1.0")]
public partial class UpdateGlAccountItem : CreateGlAccountItem {
    
    private int glAccountIdField;
    
    /// <remarks/>
    public int GlAccountId {
        get {
            return this.glAccountIdField;
        }
        set {
            this.glAccountIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://data.matrix.financials.fivedegrees.nl/1.0")]
public partial class GlAccountItem {
    
    private int glAccountIdField;
    
    private string accountNameField;
    
    private string descriptionField;
    
    private System.Nullable<GlAccountTypes> glAccountTypeField;
    
    private bool glAccountTypeFieldSpecified;
    
    private string externalAccountField;
    
    private System.Nullable<GlAccountsMappingRules> glAccountMappingRuleField;
    
    private bool glAccountMappingRuleFieldSpecified;
    
    private long transactionIdField;
    
    private bool transactionIdFieldSpecified;
    
    private EntityInfoItem entityInfoField;
    
    /// <remarks/>
    public int GlAccountId {
        get {
            return this.glAccountIdField;
        }
        set {
            this.glAccountIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string AccountName {
        get {
            return this.accountNameField;
        }
        set {
            this.accountNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<GlAccountTypes> GlAccountType {
        get {
            return this.glAccountTypeField;
        }
        set {
            this.glAccountTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool GlAccountTypeSpecified {
        get {
            return this.glAccountTypeFieldSpecified;
        }
        set {
            this.glAccountTypeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ExternalAccount {
        get {
            return this.externalAccountField;
        }
        set {
            this.externalAccountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<GlAccountsMappingRules> GlAccountMappingRule {
        get {
            return this.glAccountMappingRuleField;
        }
        set {
            this.glAccountMappingRuleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool GlAccountMappingRuleSpecified {
        get {
            return this.glAccountMappingRuleFieldSpecified;
        }
        set {
            this.glAccountMappingRuleFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public long TransactionId {
        get {
            return this.transactionIdField;
        }
        set {
            this.transactionIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TransactionIdSpecified {
        get {
            return this.transactionIdFieldSpecified;
        }
        set {
            this.transactionIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public EntityInfoItem EntityInfo {
        get {
            return this.entityInfoField;
        }
        set {
            this.entityInfoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://data.matrix.financials.fivedegrees.nl/1.0")]
public partial class EntityInfoItem {
    
    private EventDateItem createdField;
    
    private EventDateItem changedField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public EventDateItem Created {
        get {
            return this.createdField;
        }
        set {
            this.createdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public EventDateItem Changed {
        get {
            return this.changedField;
        }
        set {
            this.changedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://data.matrix.financials.fivedegrees.nl/1.0")]
public partial class EventDateItem {
    
    private System.Nullable<int> userIdField;
    
    private bool userIdFieldSpecified;
    
    private string userNameField;
    
    private System.Nullable<System.DateTime> eventDateField;
    
    private bool eventDateFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> UserId {
        get {
            return this.userIdField;
        }
        set {
            this.userIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UserIdSpecified {
        get {
            return this.userIdFieldSpecified;
        }
        set {
            this.userIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string UserName {
        get {
            return this.userNameField;
        }
        set {
            this.userNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> EventDate {
        get {
            return this.eventDateField;
        }
        set {
            this.eventDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool EventDateSpecified {
        get {
            return this.eventDateFieldSpecified;
        }
        set {
            this.eventDateFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:OperationResult")]
public partial class OperationResult_ArrayOfGlAccountItem {
    
    private int resultCodeField;
    
    private long operationIdField;
    
    private string errorMessageField;
    
    private GlAccountItem[] dataField;
    
    private int centerIdField;
    
    private OperationStatuses statusField;
    
    private bool statusFieldSpecified;
    
    private bool waitingApprovalField;
    
    /// <remarks/>
    public int ResultCode {
        get {
            return this.resultCodeField;
        }
        set {
            this.resultCodeField = value;
        }
    }
    
    /// <remarks/>
    public long OperationId {
        get {
            return this.operationIdField;
        }
        set {
            this.operationIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ErrorMessage {
        get {
            return this.errorMessageField;
        }
        set {
            this.errorMessageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://data.matrix.financials.fivedegrees.nl/1.0")]
    public GlAccountItem[] Data {
        get {
            return this.dataField;
        }
        set {
            this.dataField = value;
        }
    }
    
    /// <remarks/>
    public int CenterId {
        get {
            return this.centerIdField;
        }
        set {
            this.centerIdField = value;
        }
    }
    
    /// <remarks/>
    public OperationStatuses Status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StatusSpecified {
        get {
            return this.statusFieldSpecified;
        }
        set {
            this.statusFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool WaitingApproval {
        get {
            return this.waitingApprovalField;
        }
        set {
            this.waitingApprovalField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://data.matrix.financials.fivedegrees.nl/1.0")]
public partial class BalanceSheetListItem {
    
    private System.DateTime dateField;
    
    private string balanceSheetTypeField;
    
    private string centerField;
    
    private string departmentField;
    
    private string unitField;
    
    private string productField;
    
    private string currencyField;
    
    private decimal balanceField;
    
    private string operationalCurrencyField;
    
    /// <remarks/>
    public System.DateTime Date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string BalanceSheetType {
        get {
            return this.balanceSheetTypeField;
        }
        set {
            this.balanceSheetTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Center {
        get {
            return this.centerField;
        }
        set {
            this.centerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Department {
        get {
            return this.departmentField;
        }
        set {
            this.departmentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Unit {
        get {
            return this.unitField;
        }
        set {
            this.unitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Product {
        get {
            return this.productField;
        }
        set {
            this.productField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Currency {
        get {
            return this.currencyField;
        }
        set {
            this.currencyField = value;
        }
    }
    
    /// <remarks/>
    public decimal Balance {
        get {
            return this.balanceField;
        }
        set {
            this.balanceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string OperationalCurrency {
        get {
            return this.operationalCurrencyField;
        }
        set {
            this.operationalCurrencyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:OperationResult")]
public partial class OperationResult_ArrayOfBalanceSheetListItem {
    
    private int resultCodeField;
    
    private long operationIdField;
    
    private string errorMessageField;
    
    private BalanceSheetListItem[] dataField;
    
    private int centerIdField;
    
    private OperationStatuses statusField;
    
    private bool statusFieldSpecified;
    
    private bool waitingApprovalField;
    
    /// <remarks/>
    public int ResultCode {
        get {
            return this.resultCodeField;
        }
        set {
            this.resultCodeField = value;
        }
    }
    
    /// <remarks/>
    public long OperationId {
        get {
            return this.operationIdField;
        }
        set {
            this.operationIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ErrorMessage {
        get {
            return this.errorMessageField;
        }
        set {
            this.errorMessageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://data.matrix.financials.fivedegrees.nl/1.0")]
    public BalanceSheetListItem[] Data {
        get {
            return this.dataField;
        }
        set {
            this.dataField = value;
        }
    }
    
    /// <remarks/>
    public int CenterId {
        get {
            return this.centerIdField;
        }
        set {
            this.centerIdField = value;
        }
    }
    
    /// <remarks/>
    public OperationStatuses Status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StatusSpecified {
        get {
            return this.statusFieldSpecified;
        }
        set {
            this.statusFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool WaitingApproval {
        get {
            return this.waitingApprovalField;
        }
        set {
            this.waitingApprovalField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://data.matrix.financials.fivedegrees.nl/1.0")]
public partial class BalanceSheetEntryListItem {
    
    private System.DateTime dateField;
    
    private string centerField;
    
    private string departmentField;
    
    private string unitField;
    
    private string serviceField;
    
    private string currencyField;
    
    private decimal nominalAmountField;
    
    private decimal accruedInterestField;
    
    private string operationalCurrencyField;
    
    private int portfolioField;
    
    private string productField;
    
    private int interestSchemeIdField;
    
    private int feeSchemeIdField;
    
    private int taxSchemeIdField;
    
    private EntityInfoItem entityInfoField;
    
    private decimal interestRateField;
    
    private bool interestRateFieldSpecified;
    
    /// <remarks/>
    public System.DateTime Date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Center {
        get {
            return this.centerField;
        }
        set {
            this.centerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Department {
        get {
            return this.departmentField;
        }
        set {
            this.departmentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Unit {
        get {
            return this.unitField;
        }
        set {
            this.unitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Service {
        get {
            return this.serviceField;
        }
        set {
            this.serviceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Currency {
        get {
            return this.currencyField;
        }
        set {
            this.currencyField = value;
        }
    }
    
    /// <remarks/>
    public decimal NominalAmount {
        get {
            return this.nominalAmountField;
        }
        set {
            this.nominalAmountField = value;
        }
    }
    
    /// <remarks/>
    public decimal AccruedInterest {
        get {
            return this.accruedInterestField;
        }
        set {
            this.accruedInterestField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string OperationalCurrency {
        get {
            return this.operationalCurrencyField;
        }
        set {
            this.operationalCurrencyField = value;
        }
    }
    
    /// <remarks/>
    public int Portfolio {
        get {
            return this.portfolioField;
        }
        set {
            this.portfolioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Product {
        get {
            return this.productField;
        }
        set {
            this.productField = value;
        }
    }
    
    /// <remarks/>
    public int InterestSchemeId {
        get {
            return this.interestSchemeIdField;
        }
        set {
            this.interestSchemeIdField = value;
        }
    }
    
    /// <remarks/>
    public int FeeSchemeId {
        get {
            return this.feeSchemeIdField;
        }
        set {
            this.feeSchemeIdField = value;
        }
    }
    
    /// <remarks/>
    public int TaxSchemeId {
        get {
            return this.taxSchemeIdField;
        }
        set {
            this.taxSchemeIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public EntityInfoItem EntityInfo {
        get {
            return this.entityInfoField;
        }
        set {
            this.entityInfoField = value;
        }
    }
    
    /// <remarks/>
    public decimal InterestRate {
        get {
            return this.interestRateField;
        }
        set {
            this.interestRateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool InterestRateSpecified {
        get {
            return this.interestRateFieldSpecified;
        }
        set {
            this.interestRateFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:OperationResult")]
public partial class OperationResult_ArrayOfBalanceSheetEntryListItem {
    
    private int resultCodeField;
    
    private long operationIdField;
    
    private string errorMessageField;
    
    private BalanceSheetEntryListItem[] dataField;
    
    private int centerIdField;
    
    private OperationStatuses statusField;
    
    private bool statusFieldSpecified;
    
    private bool waitingApprovalField;
    
    /// <remarks/>
    public int ResultCode {
        get {
            return this.resultCodeField;
        }
        set {
            this.resultCodeField = value;
        }
    }
    
    /// <remarks/>
    public long OperationId {
        get {
            return this.operationIdField;
        }
        set {
            this.operationIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ErrorMessage {
        get {
            return this.errorMessageField;
        }
        set {
            this.errorMessageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://data.matrix.financials.fivedegrees.nl/1.0")]
    public BalanceSheetEntryListItem[] Data {
        get {
            return this.dataField;
        }
        set {
            this.dataField = value;
        }
    }
    
    /// <remarks/>
    public int CenterId {
        get {
            return this.centerIdField;
        }
        set {
            this.centerIdField = value;
        }
    }
    
    /// <remarks/>
    public OperationStatuses Status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StatusSpecified {
        get {
            return this.statusFieldSpecified;
        }
        set {
            this.statusFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool WaitingApproval {
        get {
            return this.waitingApprovalField;
        }
        set {
            this.waitingApprovalField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://data.matrix.financials.fivedegrees.nl/1.0")]
public partial class AccountIdentifierItem {
    
    private IdentificationStandards identificationStandardField;
    
    private bool identificationStandardFieldSpecified;
    
    private string identifierField;
    
    /// <remarks/>
    public IdentificationStandards IdentificationStandard {
        get {
            return this.identificationStandardField;
        }
        set {
            this.identificationStandardField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IdentificationStandardSpecified {
        get {
            return this.identificationStandardFieldSpecified;
        }
        set {
            this.identificationStandardFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Identifier {
        get {
            return this.identifierField;
        }
        set {
            this.identifierField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://data.matrix.financials.fivedegrees.nl/1.0")]
public enum IdentificationStandards {
    
    /// <remarks/>
    Internal,
    
    /// <remarks/>
    SWIFT,
    
    /// <remarks/>
    IBAN,
    
    /// <remarks/>
    TARGET,
    
    /// <remarks/>
    BBAN,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://data.matrix.financials.fivedegrees.nl/1.0")]
public partial class JournalEntryListItem {
    
    private System.DateTime dateField;
    
    private AccountIdentifierItem[] serviceIdentifiersField;
    
    private string productField;
    
    private decimal amountField;
    
    private string currencyField;
    
    private decimal exchangeRateField;
    
    private string operationalCurrencyField;
    
    private string paymentTypeField;
    
    private string centerField;
    
    private string departmentField;
    
    private string unitField;
    
    private string accountField;
    
    private string accountTypeField;
    
    private bool isDebitField;
    
    private EntityInfoItem entityInfoField;
    
    /// <remarks/>
    public System.DateTime Date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    public AccountIdentifierItem[] ServiceIdentifiers {
        get {
            return this.serviceIdentifiersField;
        }
        set {
            this.serviceIdentifiersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Product {
        get {
            return this.productField;
        }
        set {
            this.productField = value;
        }
    }
    
    /// <remarks/>
    public decimal Amount {
        get {
            return this.amountField;
        }
        set {
            this.amountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Currency {
        get {
            return this.currencyField;
        }
        set {
            this.currencyField = value;
        }
    }
    
    /// <remarks/>
    public decimal ExchangeRate {
        get {
            return this.exchangeRateField;
        }
        set {
            this.exchangeRateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string OperationalCurrency {
        get {
            return this.operationalCurrencyField;
        }
        set {
            this.operationalCurrencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string PaymentType {
        get {
            return this.paymentTypeField;
        }
        set {
            this.paymentTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Center {
        get {
            return this.centerField;
        }
        set {
            this.centerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Department {
        get {
            return this.departmentField;
        }
        set {
            this.departmentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Unit {
        get {
            return this.unitField;
        }
        set {
            this.unitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Account {
        get {
            return this.accountField;
        }
        set {
            this.accountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string AccountType {
        get {
            return this.accountTypeField;
        }
        set {
            this.accountTypeField = value;
        }
    }
    
    /// <remarks/>
    public bool IsDebit {
        get {
            return this.isDebitField;
        }
        set {
            this.isDebitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public EntityInfoItem EntityInfo {
        get {
            return this.entityInfoField;
        }
        set {
            this.entityInfoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:OperationResult")]
public partial class OperationResult_ArrayOfJournalEntryListItem {
    
    private int resultCodeField;
    
    private long operationIdField;
    
    private string errorMessageField;
    
    private JournalEntryListItem[] dataField;
    
    private int centerIdField;
    
    private OperationStatuses statusField;
    
    private bool statusFieldSpecified;
    
    private bool waitingApprovalField;
    
    /// <remarks/>
    public int ResultCode {
        get {
            return this.resultCodeField;
        }
        set {
            this.resultCodeField = value;
        }
    }
    
    /// <remarks/>
    public long OperationId {
        get {
            return this.operationIdField;
        }
        set {
            this.operationIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ErrorMessage {
        get {
            return this.errorMessageField;
        }
        set {
            this.errorMessageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://data.matrix.financials.fivedegrees.nl/1.0")]
    public JournalEntryListItem[] Data {
        get {
            return this.dataField;
        }
        set {
            this.dataField = value;
        }
    }
    
    /// <remarks/>
    public int CenterId {
        get {
            return this.centerIdField;
        }
        set {
            this.centerIdField = value;
        }
    }
    
    /// <remarks/>
    public OperationStatuses Status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StatusSpecified {
        get {
            return this.statusFieldSpecified;
        }
        set {
            this.statusFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool WaitingApproval {
        get {
            return this.waitingApprovalField;
        }
        set {
            this.waitingApprovalField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://data.matrix.financials.fivedegrees.nl/1.0")]
public enum BalanceSheetEntryTypes {
    
    /// <remarks/>
    BusinessDay,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void CheckCompletedEventHandler(object sender, CheckCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CheckCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal CheckCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public HealthCheckItem Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((HealthCheckItem)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void GetJournalEntriesCompletedEventHandler(object sender, GetJournalEntriesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetJournalEntriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetJournalEntriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public OperationResult_ArrayOfJournalEntryListItem Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((OperationResult_ArrayOfJournalEntryListItem)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void GetBalanceSheetEntriesCompletedEventHandler(object sender, GetBalanceSheetEntriesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetBalanceSheetEntriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetBalanceSheetEntriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public OperationResult_ArrayOfBalanceSheetEntryListItem Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((OperationResult_ArrayOfBalanceSheetEntryListItem)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void GetBalanceSheetCompletedEventHandler(object sender, GetBalanceSheetCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetBalanceSheetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetBalanceSheetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public OperationResult_ArrayOfBalanceSheetListItem Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((OperationResult_ArrayOfBalanceSheetListItem)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void GetGlAccountsCompletedEventHandler(object sender, GetGlAccountsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetGlAccountsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetGlAccountsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public OperationResult_ArrayOfGlAccountItem Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((OperationResult_ArrayOfGlAccountItem)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void CreateGlAccountCompletedEventHandler(object sender, CreateGlAccountCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CreateGlAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal CreateGlAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public OperationResult_int Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((OperationResult_int)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void UpdateGlAccountCompletedEventHandler(object sender, UpdateGlAccountCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class UpdateGlAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal UpdateGlAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public OperationResult_boolean Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((OperationResult_boolean)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void DeleteGlAccountCompletedEventHandler(object sender, DeleteGlAccountCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class DeleteGlAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal DeleteGlAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public OperationResult_boolean Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((OperationResult_boolean)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void UpdateGlAccountsForServicesCompletedEventHandler(object sender, UpdateGlAccountsForServicesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class UpdateGlAccountsForServicesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal UpdateGlAccountsForServicesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public OperationResult_boolean Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((OperationResult_boolean)(this.results[0]));
        }
    }
}
