//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BND.Services.IbanStore.ServiceTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BND.Services.IbanStore.ServiceTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 548751870
        ///525406719
        ///441417043
        ///725354534
        ///341603562.
        /// </summary>
        internal static string BBANFile_Sample {
            get {
                return ResourceManager.GetString("BBANFile_Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///Deployment script for Bndb.IBanStore.Db
        ///
        ///This code was generated by a tool.
        ///Changes to this file may cause incorrect behavior and will be lost if
        ///the code is regenerated.
        ///*/
        ///
        ///GO
        ///SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;
        ///
        ///SET NUMERIC_ROUNDABORT OFF;
        ///
        ///
        ///GO
        ///:setvar DatabaseName &quot;Bndb.IBanStore.Db.Test&quot;
        ///:setvar DefaultFilePrefix &quot;Bndb.IBanStore.Db.Test&quot;
        ///:setvar DefaultDataPath &quot;&quot;
        ///:setvar DefaultLogPath &quot;&quot;
        ///
        ///GO
        ///:on error exit
        ///GO [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Bndb_IBanStore_Db_Create {
            get {
                return ResourceManager.GetString("Bndb_IBanStore_Db_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;Setting&gt;
        ///    &lt;EmailSetting&gt;
        ///		&lt;MailManComponentCode&gt;BRANDNMAILQ_CZKwC83c5P3M&lt;/MailManComponentCode&gt;
        ///		&lt;EmailServer&gt;smtp.gmail.com&lt;/EmailServer&gt;
        ///		&lt;EmailSmtpPort&gt;465&lt;/EmailSmtpPort&gt;
        ///		&lt;EmailAccount&gt;kobkiat.peace@gmail.com&lt;/EmailAccount&gt;
        ///		&lt;EmailPassword&gt;qwerty@12345&lt;/EmailPassword&gt;
        ///	&lt;/EmailSetting&gt;
        ///&lt;/Setting&gt;.
        /// </summary>
        internal static string ConfigurationFile {
            get {
                return ResourceManager.GetString("ConfigurationFile", resourceCulture);
            }
        }
    }
}
